// Code generated by ent, DO NOT EDIT.

package workitemlabel

import (
	"my-jira/apps/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldEQ(FieldDeletedAt, v))
}

// WorkspaceID applies equality check predicate on the "workspace_id" field. It's identical to WorkspaceIDEQ.
func WorkspaceID(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldEQ(FieldWorkspaceID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldEQ(FieldProjectID, v))
}

// WorkItemID applies equality check predicate on the "work_item_id" field. It's identical to WorkItemIDEQ.
func WorkItemID(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldEQ(FieldWorkItemID, v))
}

// LabelID applies equality check predicate on the "label_id" field. It's identical to LabelIDEQ.
func LabelID(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldEQ(FieldLabelID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldNotNull(FieldDeletedAt))
}

// WorkspaceIDEQ applies the EQ predicate on the "workspace_id" field.
func WorkspaceIDEQ(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldEQ(FieldWorkspaceID, v))
}

// WorkspaceIDNEQ applies the NEQ predicate on the "workspace_id" field.
func WorkspaceIDNEQ(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldNEQ(FieldWorkspaceID, v))
}

// WorkspaceIDIn applies the In predicate on the "workspace_id" field.
func WorkspaceIDIn(vs ...uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDNotIn applies the NotIn predicate on the "workspace_id" field.
func WorkspaceIDNotIn(vs ...uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldNotIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDGT applies the GT predicate on the "workspace_id" field.
func WorkspaceIDGT(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldGT(FieldWorkspaceID, v))
}

// WorkspaceIDGTE applies the GTE predicate on the "workspace_id" field.
func WorkspaceIDGTE(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldGTE(FieldWorkspaceID, v))
}

// WorkspaceIDLT applies the LT predicate on the "workspace_id" field.
func WorkspaceIDLT(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldLT(FieldWorkspaceID, v))
}

// WorkspaceIDLTE applies the LTE predicate on the "workspace_id" field.
func WorkspaceIDLTE(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldLTE(FieldWorkspaceID, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldLTE(FieldProjectID, v))
}

// WorkItemIDEQ applies the EQ predicate on the "work_item_id" field.
func WorkItemIDEQ(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldEQ(FieldWorkItemID, v))
}

// WorkItemIDNEQ applies the NEQ predicate on the "work_item_id" field.
func WorkItemIDNEQ(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldNEQ(FieldWorkItemID, v))
}

// WorkItemIDIn applies the In predicate on the "work_item_id" field.
func WorkItemIDIn(vs ...uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldIn(FieldWorkItemID, vs...))
}

// WorkItemIDNotIn applies the NotIn predicate on the "work_item_id" field.
func WorkItemIDNotIn(vs ...uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldNotIn(FieldWorkItemID, vs...))
}

// WorkItemIDGT applies the GT predicate on the "work_item_id" field.
func WorkItemIDGT(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldGT(FieldWorkItemID, v))
}

// WorkItemIDGTE applies the GTE predicate on the "work_item_id" field.
func WorkItemIDGTE(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldGTE(FieldWorkItemID, v))
}

// WorkItemIDLT applies the LT predicate on the "work_item_id" field.
func WorkItemIDLT(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldLT(FieldWorkItemID, v))
}

// WorkItemIDLTE applies the LTE predicate on the "work_item_id" field.
func WorkItemIDLTE(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldLTE(FieldWorkItemID, v))
}

// LabelIDEQ applies the EQ predicate on the "label_id" field.
func LabelIDEQ(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldEQ(FieldLabelID, v))
}

// LabelIDNEQ applies the NEQ predicate on the "label_id" field.
func LabelIDNEQ(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldNEQ(FieldLabelID, v))
}

// LabelIDIn applies the In predicate on the "label_id" field.
func LabelIDIn(vs ...uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldIn(FieldLabelID, vs...))
}

// LabelIDNotIn applies the NotIn predicate on the "label_id" field.
func LabelIDNotIn(vs ...uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldNotIn(FieldLabelID, vs...))
}

// LabelIDGT applies the GT predicate on the "label_id" field.
func LabelIDGT(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldGT(FieldLabelID, v))
}

// LabelIDGTE applies the GTE predicate on the "label_id" field.
func LabelIDGTE(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldGTE(FieldLabelID, v))
}

// LabelIDLT applies the LT predicate on the "label_id" field.
func LabelIDLT(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldLT(FieldLabelID, v))
}

// LabelIDLTE applies the LTE predicate on the "label_id" field.
func LabelIDLTE(v uuid.UUID) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.FieldLTE(FieldLabelID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkItemLabel) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkItemLabel) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkItemLabel) predicate.WorkItemLabel {
	return predicate.WorkItemLabel(sql.NotPredicates(p))
}
