// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APITokensColumns holds the columns for the "api_tokens" table.
	APITokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "token_hash", Type: field.TypeString},
		{Name: "prefix", Type: field.TypeString},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
	}
	// APITokensTable holds the schema information for the "api_tokens" table.
	APITokensTable = &schema.Table{
		Name:       "api_tokens",
		Columns:    APITokensColumns,
		PrimaryKey: []*schema.Column{APITokensColumns[0]},
	}
	// ActivitiesColumns holds the columns for the "activities" table.
	ActivitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID, Nullable: true},
		{Name: "work_item_id", Type: field.TypeUUID, Nullable: true},
		{Name: "actor_id", Type: field.TypeUUID},
		{Name: "action", Type: field.TypeString},
		{Name: "field_name", Type: field.TypeString, Default: ""},
		{Name: "old_value", Type: field.TypeJSON, Nullable: true},
		{Name: "new_value", Type: field.TypeJSON, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON},
	}
	// ActivitiesTable holds the schema information for the "activities" table.
	ActivitiesTable = &schema.Table{
		Name:       "activities",
		Columns:    ActivitiesColumns,
		PrimaryKey: []*schema.Column{ActivitiesColumns[0]},
	}
	// AuthChallengesColumns holds the columns for the "auth_challenges" table.
	AuthChallengesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeUUID, Nullable: true},
		{Name: "email", Type: field.TypeString},
		{Name: "purpose", Type: field.TypeString},
		{Name: "token_hash", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "consumed_at", Type: field.TypeTime, Nullable: true},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "metadata", Type: field.TypeJSON},
	}
	// AuthChallengesTable holds the schema information for the "auth_challenges" table.
	AuthChallengesTable = &schema.Table{
		Name:       "auth_challenges",
		Columns:    AuthChallengesColumns,
		PrimaryKey: []*schema.Column{AuthChallengesColumns[0]},
	}
	// AuthRateLimitsColumns holds the columns for the "auth_rate_limits" table.
	AuthRateLimitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "window_started", Type: field.TypeTime},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
	}
	// AuthRateLimitsTable holds the schema information for the "auth_rate_limits" table.
	AuthRateLimitsTable = &schema.Table{
		Name:       "auth_rate_limits",
		Columns:    AuthRateLimitsColumns,
		PrimaryKey: []*schema.Column{AuthRateLimitsColumns[0]},
	}
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "work_item_id", Type: field.TypeUUID},
		{Name: "parent_id", Type: field.TypeUUID, Nullable: true},
		{Name: "author_id", Type: field.TypeUUID},
		{Name: "body_html", Type: field.TypeString, Default: "<p></p>"},
		{Name: "body_json", Type: field.TypeJSON},
		{Name: "edited_at", Type: field.TypeTime, Nullable: true},
		{Name: "is_public", Type: field.TypeBool, Default: false},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
	}
	// CyclesColumns holds the columns for the "cycles" table.
	CyclesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "start_date", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "end_date", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "owner_id", Type: field.TypeUUID},
		{Name: "position", Type: field.TypeFloat64, Default: 65536},
		{Name: "archived_at", Type: field.TypeTime, Nullable: true},
		{Name: "settings", Type: field.TypeJSON},
		{Name: "progress_snapshot", Type: field.TypeJSON, Nullable: true},
	}
	// CyclesTable holds the schema information for the "cycles" table.
	CyclesTable = &schema.Table{
		Name:       "cycles",
		Columns:    CyclesColumns,
		PrimaryKey: []*schema.Column{CyclesColumns[0]},
	}
	// CycleItemsColumns holds the columns for the "cycle_items" table.
	CycleItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "cycle_id", Type: field.TypeUUID},
		{Name: "work_item_id", Type: field.TypeUUID},
	}
	// CycleItemsTable holds the schema information for the "cycle_items" table.
	CycleItemsTable = &schema.Table{
		Name:       "cycle_items",
		Columns:    CycleItemsColumns,
		PrimaryKey: []*schema.Column{CycleItemsColumns[0]},
	}
	// EstimatesColumns holds the columns for the "estimates" table.
	EstimatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "kind", Type: field.TypeString, Default: "points"},
	}
	// EstimatesTable holds the schema information for the "estimates" table.
	EstimatesTable = &schema.Table{
		Name:       "estimates",
		Columns:    EstimatesColumns,
		PrimaryKey: []*schema.Column{EstimatesColumns[0]},
	}
	// EstimatePointsColumns holds the columns for the "estimate_points" table.
	EstimatePointsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "estimate_id", Type: field.TypeUUID},
		{Name: "position", Type: field.TypeFloat64, Default: 1024},
		{Name: "label", Type: field.TypeString, Size: 20},
		{Name: "numeric_value", Type: field.TypeFloat64, Nullable: true},
	}
	// EstimatePointsTable holds the schema information for the "estimate_points" table.
	EstimatePointsTable = &schema.Table{
		Name:       "estimate_points",
		Columns:    EstimatePointsColumns,
		PrimaryKey: []*schema.Column{EstimatePointsColumns[0]},
	}
	// ExportsColumns holds the columns for the "exports" table.
	ExportsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID, Nullable: true},
		{Name: "requested_by", Type: field.TypeUUID},
		{Name: "format", Type: field.TypeString},
		{Name: "filters", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "object_key", Type: field.TypeString, Default: ""},
		{Name: "error_message", Type: field.TypeString, Default: ""},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
	}
	// ExportsTable holds the schema information for the "exports" table.
	ExportsTable = &schema.Table{
		Name:       "exports",
		Columns:    ExportsColumns,
		PrimaryKey: []*schema.Column{ExportsColumns[0]},
	}
	// FavoritesColumns holds the columns for the "favorites" table.
	FavoritesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "entity_type", Type: field.TypeString},
		{Name: "entity_id", Type: field.TypeUUID},
		{Name: "position", Type: field.TypeFloat64, Default: 65536},
	}
	// FavoritesTable holds the schema information for the "favorites" table.
	FavoritesTable = &schema.Table{
		Name:       "favorites",
		Columns:    FavoritesColumns,
		PrimaryKey: []*schema.Column{FavoritesColumns[0]},
	}
	// FileAssetsColumns holds the columns for the "file_assets" table.
	FileAssetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID, Nullable: true},
		{Name: "project_id", Type: field.TypeUUID, Nullable: true},
		{Name: "work_item_id", Type: field.TypeUUID, Nullable: true},
		{Name: "page_id", Type: field.TypeUUID, Nullable: true},
		{Name: "uploaded_by", Type: field.TypeUUID},
		{Name: "filename", Type: field.TypeString},
		{Name: "content_type", Type: field.TypeString},
		{Name: "size_bytes", Type: field.TypeInt64},
		{Name: "object_key", Type: field.TypeString},
		{Name: "upload_status", Type: field.TypeString, Default: "pending"},
		{Name: "metadata", Type: field.TypeJSON},
	}
	// FileAssetsTable holds the schema information for the "file_assets" table.
	FileAssetsTable = &schema.Table{
		Name:       "file_assets",
		Columns:    FileAssetsColumns,
		PrimaryKey: []*schema.Column{FileAssetsColumns[0]},
	}
	// InstancesColumns holds the columns for the "instances" table.
	InstancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "singleton", Type: field.TypeBool, Default: true},
		{Name: "name", Type: field.TypeString},
		{Name: "registration_enabled", Type: field.TypeBool, Default: true},
		{Name: "setup_by", Type: field.TypeUUID},
		{Name: "settings", Type: field.TypeJSON},
	}
	// InstancesTable holds the schema information for the "instances" table.
	InstancesTable = &schema.Table{
		Name:       "instances",
		Columns:    InstancesColumns,
		PrimaryKey: []*schema.Column{InstancesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "instance_singleton",
				Unique:  true,
				Columns: []*schema.Column{InstancesColumns[4]},
			},
		},
	}
	// IntakeItemsColumns holds the columns for the "intake_items" table.
	IntakeItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "work_item_id", Type: field.TypeUUID},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "source", Type: field.TypeString, Default: "app"},
		{Name: "submitted_by", Type: field.TypeUUID},
		{Name: "duplicate_of", Type: field.TypeUUID, Nullable: true},
		{Name: "snoozed_until", Type: field.TypeTime, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON},
	}
	// IntakeItemsTable holds the schema information for the "intake_items" table.
	IntakeItemsTable = &schema.Table{
		Name:       "intake_items",
		Columns:    IntakeItemsColumns,
		PrimaryKey: []*schema.Column{IntakeItemsColumns[0]},
	}
	// InvitationsColumns holds the columns for the "invitations" table.
	InvitationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString},
		{Name: "role", Type: field.TypeInt, Default: 15},
		{Name: "token_hash", Type: field.TypeString},
		{Name: "invited_by", Type: field.TypeUUID},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "accepted_at", Type: field.TypeTime, Nullable: true},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
	}
	// InvitationsTable holds the schema information for the "invitations" table.
	InvitationsTable = &schema.Table{
		Name:       "invitations",
		Columns:    InvitationsColumns,
		PrimaryKey: []*schema.Column{InvitationsColumns[0]},
	}
	// LabelsColumns holds the columns for the "labels" table.
	LabelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID, Nullable: true},
		{Name: "parent_id", Type: field.TypeUUID, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "color", Type: field.TypeString, Default: "#64748b"},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "position", Type: field.TypeFloat64, Default: 65536},
	}
	// LabelsTable holds the schema information for the "labels" table.
	LabelsTable = &schema.Table{
		Name:       "labels",
		Columns:    LabelsColumns,
		PrimaryKey: []*schema.Column{LabelsColumns[0]},
	}
	// ModulesColumns holds the columns for the "modules" table.
	ModulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: "planned"},
		{Name: "start_date", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "target_date", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "lead_id", Type: field.TypeUUID, Nullable: true},
		{Name: "position", Type: field.TypeFloat64, Default: 65536},
		{Name: "archived_at", Type: field.TypeTime, Nullable: true},
		{Name: "settings", Type: field.TypeJSON},
	}
	// ModulesTable holds the schema information for the "modules" table.
	ModulesTable = &schema.Table{
		Name:       "modules",
		Columns:    ModulesColumns,
		PrimaryKey: []*schema.Column{ModulesColumns[0]},
	}
	// ModuleItemsColumns holds the columns for the "module_items" table.
	ModuleItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "module_id", Type: field.TypeUUID},
		{Name: "work_item_id", Type: field.TypeUUID},
	}
	// ModuleItemsTable holds the schema information for the "module_items" table.
	ModuleItemsTable = &schema.Table{
		Name:       "module_items",
		Columns:    ModuleItemsColumns,
		PrimaryKey: []*schema.Column{ModuleItemsColumns[0]},
	}
	// ModuleLinksColumns holds the columns for the "module_links" table.
	ModuleLinksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "module_id", Type: field.TypeUUID},
		{Name: "created_by", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "url", Type: field.TypeString, Size: 4096},
	}
	// ModuleLinksTable holds the schema information for the "module_links" table.
	ModuleLinksTable = &schema.Table{
		Name:       "module_links",
		Columns:    ModuleLinksColumns,
		PrimaryKey: []*schema.Column{ModuleLinksColumns[0]},
	}
	// ModuleMembersColumns holds the columns for the "module_members" table.
	ModuleMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "module_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// ModuleMembersTable holds the schema information for the "module_members" table.
	ModuleMembersTable = &schema.Table{
		Name:       "module_members",
		Columns:    ModuleMembersColumns,
		PrimaryKey: []*schema.Column{ModuleMembersColumns[0]},
	}
	// NotificationsColumns holds the columns for the "notifications" table.
	NotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID, Nullable: true},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "actor_id", Type: field.TypeUUID, Nullable: true},
		{Name: "entity_type", Type: field.TypeString},
		{Name: "entity_id", Type: field.TypeUUID, Nullable: true},
		{Name: "title", Type: field.TypeString},
		{Name: "body", Type: field.TypeString, Default: ""},
		{Name: "data", Type: field.TypeJSON},
		{Name: "read_at", Type: field.TypeTime, Nullable: true},
		{Name: "archived_at", Type: field.TypeTime, Nullable: true},
		{Name: "snoozed_until", Type: field.TypeTime, Nullable: true},
	}
	// NotificationsTable holds the schema information for the "notifications" table.
	NotificationsTable = &schema.Table{
		Name:       "notifications",
		Columns:    NotificationsColumns,
		PrimaryKey: []*schema.Column{NotificationsColumns[0]},
	}
	// OauthAccountsColumns holds the columns for the "oauth_accounts" table.
	OauthAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "provider", Type: field.TypeString},
		{Name: "subject", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "metadata", Type: field.TypeJSON},
	}
	// OauthAccountsTable holds the schema information for the "oauth_accounts" table.
	OauthAccountsTable = &schema.Table{
		Name:       "oauth_accounts",
		Columns:    OauthAccountsColumns,
		PrimaryKey: []*schema.Column{OauthAccountsColumns[0]},
	}
	// OutboxEventsColumns holds the columns for the "outbox_events" table.
	OutboxEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "topic", Type: field.TypeString},
		{Name: "payload", Type: field.TypeJSON},
		{Name: "deduplication_key", Type: field.TypeString, Unique: true},
		{Name: "dispatched_at", Type: field.TypeTime, Nullable: true},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "last_error", Type: field.TypeString, Default: ""},
	}
	// OutboxEventsTable holds the schema information for the "outbox_events" table.
	OutboxEventsTable = &schema.Table{
		Name:       "outbox_events",
		Columns:    OutboxEventsColumns,
		PrimaryKey: []*schema.Column{OutboxEventsColumns[0]},
	}
	// PagesColumns holds the columns for the "pages" table.
	PagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID, Nullable: true},
		{Name: "parent_id", Type: field.TypeUUID, Nullable: true},
		{Name: "owner_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "content_html", Type: field.TypeString, Default: "<p></p>"},
		{Name: "content_json", Type: field.TypeJSON},
		{Name: "content_binary", Type: field.TypeBytes, Nullable: true},
		{Name: "is_private", Type: field.TypeBool, Default: false},
		{Name: "is_locked", Type: field.TypeBool, Default: false},
		{Name: "archived_at", Type: field.TypeTime, Nullable: true},
		{Name: "position", Type: field.TypeFloat64, Default: 65536},
		{Name: "icon", Type: field.TypeString, Default: ""},
		{Name: "version", Type: field.TypeInt64, Default: 1},
	}
	// PagesTable holds the schema information for the "pages" table.
	PagesTable = &schema.Table{
		Name:       "pages",
		Columns:    PagesColumns,
		PrimaryKey: []*schema.Column{PagesColumns[0]},
	}
	// PageCommentsColumns holds the columns for the "page_comments" table.
	PageCommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID, Nullable: true},
		{Name: "page_id", Type: field.TypeUUID},
		{Name: "author_id", Type: field.TypeUUID},
		{Name: "parent_id", Type: field.TypeUUID, Nullable: true},
		{Name: "body_html", Type: field.TypeString, Default: "<p></p>"},
		{Name: "body_json", Type: field.TypeJSON},
		{Name: "edited_at", Type: field.TypeTime, Nullable: true},
	}
	// PageCommentsTable holds the schema information for the "page_comments" table.
	PageCommentsTable = &schema.Table{
		Name:       "page_comments",
		Columns:    PageCommentsColumns,
		PrimaryKey: []*schema.Column{PageCommentsColumns[0]},
	}
	// PageVersionsColumns holds the columns for the "page_versions" table.
	PageVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "page_id", Type: field.TypeUUID},
		{Name: "saved_by", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "content_html", Type: field.TypeString, Default: "<p></p>"},
		{Name: "content_json", Type: field.TypeJSON},
		{Name: "content_binary", Type: field.TypeBytes, Nullable: true},
		{Name: "version", Type: field.TypeInt64},
	}
	// PageVersionsTable holds the schema information for the "page_versions" table.
	PageVersionsTable = &schema.Table{
		Name:       "page_versions",
		Columns:    PageVersionsColumns,
		PrimaryKey: []*schema.Column{PageVersionsColumns[0]},
	}
	// PreferencesColumns holds the columns for the "preferences" table.
	PreferencesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID, Nullable: true},
		{Name: "project_id", Type: field.TypeUUID, Nullable: true},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "scope", Type: field.TypeString},
		{Name: "value", Type: field.TypeJSON},
	}
	// PreferencesTable holds the schema information for the "preferences" table.
	PreferencesTable = &schema.Table{
		Name:       "preferences",
		Columns:    PreferencesColumns,
		PrimaryKey: []*schema.Column{PreferencesColumns[0]},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "identifier", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "network", Type: field.TypeString, Default: "public"},
		{Name: "guest_can_view_all", Type: field.TypeBool, Default: false},
		{Name: "lead_id", Type: field.TypeUUID, Nullable: true},
		{Name: "default_assignee_id", Type: field.TypeUUID, Nullable: true},
		{Name: "timezone", Type: field.TypeString, Default: "UTC"},
		{Name: "icon", Type: field.TypeString, Default: ""},
		{Name: "color", Type: field.TypeString, Default: "#6d5efc"},
		{Name: "archived_at", Type: field.TypeTime, Nullable: true},
		{Name: "next_sequence", Type: field.TypeInt64, Default: 1},
		{Name: "settings", Type: field.TypeJSON},
		{Name: "estimate_id", Type: field.TypeUUID, Nullable: true},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
	}
	// ProjectMembersColumns holds the columns for the "project_members" table.
	ProjectMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "role", Type: field.TypeInt, Default: 15},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// ProjectMembersTable holds the schema information for the "project_members" table.
	ProjectMembersTable = &schema.Table{
		Name:       "project_members",
		Columns:    ProjectMembersColumns,
		PrimaryKey: []*schema.Column{ProjectMembersColumns[0]},
	}
	// PublicSitesColumns holds the columns for the "public_sites" table.
	PublicSitesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "slug", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "is_enabled", Type: field.TypeBool, Default: true},
		{Name: "comments_enabled", Type: field.TypeBool, Default: false},
		{Name: "reactions_enabled", Type: field.TypeBool, Default: false},
		{Name: "votes_enabled", Type: field.TypeBool, Default: false},
		{Name: "intake_enabled", Type: field.TypeBool, Default: false},
		{Name: "settings", Type: field.TypeJSON},
	}
	// PublicSitesTable holds the schema information for the "public_sites" table.
	PublicSitesTable = &schema.Table{
		Name:       "public_sites",
		Columns:    PublicSitesColumns,
		PrimaryKey: []*schema.Column{PublicSitesColumns[0]},
	}
	// PublicVotesColumns holds the columns for the "public_votes" table.
	PublicVotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "work_item_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// PublicVotesTable holds the schema information for the "public_votes" table.
	PublicVotesTable = &schema.Table{
		Name:       "public_votes",
		Columns:    PublicVotesColumns,
		PrimaryKey: []*schema.Column{PublicVotesColumns[0]},
	}
	// ReactionsColumns holds the columns for the "reactions" table.
	ReactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "work_item_id", Type: field.TypeUUID, Nullable: true},
		{Name: "comment_id", Type: field.TypeUUID, Nullable: true},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "emoji", Type: field.TypeString},
	}
	// ReactionsTable holds the schema information for the "reactions" table.
	ReactionsTable = &schema.Table{
		Name:       "reactions",
		Columns:    ReactionsColumns,
		PrimaryKey: []*schema.Column{ReactionsColumns[0]},
	}
	// RecentVisitsColumns holds the columns for the "recent_visits" table.
	RecentVisitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "entity_type", Type: field.TypeString},
		{Name: "entity_id", Type: field.TypeUUID},
		{Name: "visited_at", Type: field.TypeTime},
	}
	// RecentVisitsTable holds the schema information for the "recent_visits" table.
	RecentVisitsTable = &schema.Table{
		Name:       "recent_visits",
		Columns:    RecentVisitsColumns,
		PrimaryKey: []*schema.Column{RecentVisitsColumns[0]},
	}
	// SavedAnalysesColumns holds the columns for the "saved_analyses" table.
	SavedAnalysesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "owner_id", Type: field.TypeUUID},
		{Name: "query", Type: field.TypeJSON},
	}
	// SavedAnalysesTable holds the schema information for the "saved_analyses" table.
	SavedAnalysesTable = &schema.Table{
		Name:       "saved_analyses",
		Columns:    SavedAnalysesColumns,
		PrimaryKey: []*schema.Column{SavedAnalysesColumns[0]},
	}
	// SavedViewsColumns holds the columns for the "saved_views" table.
	SavedViewsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID, Nullable: true},
		{Name: "owner_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "layout", Type: field.TypeString, Default: "list"},
		{Name: "filters", Type: field.TypeJSON},
		{Name: "display", Type: field.TypeJSON},
		{Name: "is_private", Type: field.TypeBool, Default: false},
		{Name: "position", Type: field.TypeFloat64, Default: 65536},
	}
	// SavedViewsTable holds the schema information for the "saved_views" table.
	SavedViewsTable = &schema.Table{
		Name:       "saved_views",
		Columns:    SavedViewsColumns,
		PrimaryKey: []*schema.Column{SavedViewsColumns[0]},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "token_hash", Type: field.TypeString},
		{Name: "csrf_hash", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_agent", Type: field.TypeString, Default: ""},
		{Name: "ip_address", Type: field.TypeString, Default: ""},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
	}
	// StatesColumns holds the columns for the "states" table.
	StatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "color", Type: field.TypeString, Default: "#64748b"},
		{Name: "group_name", Type: field.TypeString, Default: "unstarted"},
		{Name: "position", Type: field.TypeFloat64, Default: 65536},
		{Name: "is_default", Type: field.TypeBool, Default: false},
	}
	// StatesTable holds the schema information for the "states" table.
	StatesTable = &schema.Table{
		Name:       "states",
		Columns:    StatesColumns,
		PrimaryKey: []*schema.Column{StatesColumns[0]},
	}
	// StickiesColumns holds the columns for the "stickies" table.
	StickiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "content_json", Type: field.TypeJSON},
		{Name: "content_html", Type: field.TypeString, Default: "<p></p>"},
		{Name: "color", Type: field.TypeString, Default: "#fef3c7"},
		{Name: "position", Type: field.TypeFloat64, Default: 65536},
		{Name: "is_archived", Type: field.TypeBool, Default: false},
	}
	// StickiesTable holds the schema information for the "stickies" table.
	StickiesTable = &schema.Table{
		Name:       "stickies",
		Columns:    StickiesColumns,
		PrimaryKey: []*schema.Column{StickiesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "email", Type: field.TypeString},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "password_set", Type: field.TypeBool, Default: true},
		{Name: "display_name", Type: field.TypeString, Default: ""},
		{Name: "first_name", Type: field.TypeString, Default: ""},
		{Name: "last_name", Type: field.TypeString, Default: ""},
		{Name: "avatar_url", Type: field.TypeString, Default: ""},
		{Name: "timezone", Type: field.TypeString, Default: "UTC"},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "is_instance_admin", Type: field.TypeBool, Default: false},
		{Name: "email_verified", Type: field.TypeBool, Default: false},
		{Name: "preferences", Type: field.TypeJSON},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// WebhooksColumns holds the columns for the "webhooks" table.
	WebhooksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "created_by", Type: field.TypeUUID},
		{Name: "url", Type: field.TypeString},
		{Name: "secret", Type: field.TypeString},
		{Name: "events", Type: field.TypeJSON},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// WebhooksTable holds the schema information for the "webhooks" table.
	WebhooksTable = &schema.Table{
		Name:       "webhooks",
		Columns:    WebhooksColumns,
		PrimaryKey: []*schema.Column{WebhooksColumns[0]},
	}
	// WebhookDeliveriesColumns holds the columns for the "webhook_deliveries" table.
	WebhookDeliveriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "webhook_id", Type: field.TypeUUID},
		{Name: "event_id", Type: field.TypeUUID},
		{Name: "request", Type: field.TypeJSON},
		{Name: "response_status", Type: field.TypeInt, Nullable: true},
		{Name: "response_body", Type: field.TypeString, Default: ""},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "delivered_at", Type: field.TypeTime, Nullable: true},
	}
	// WebhookDeliveriesTable holds the schema information for the "webhook_deliveries" table.
	WebhookDeliveriesTable = &schema.Table{
		Name:       "webhook_deliveries",
		Columns:    WebhookDeliveriesColumns,
		PrimaryKey: []*schema.Column{WebhookDeliveriesColumns[0]},
	}
	// WorkItemsColumns holds the columns for the "work_items" table.
	WorkItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "state_id", Type: field.TypeUUID},
		{Name: "parent_id", Type: field.TypeUUID, Nullable: true},
		{Name: "created_by", Type: field.TypeUUID},
		{Name: "updated_by", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "description_html", Type: field.TypeString, Default: "<p></p>"},
		{Name: "description_json", Type: field.TypeJSON},
		{Name: "description_binary", Type: field.TypeBytes, Nullable: true},
		{Name: "priority", Type: field.TypeString, Default: "none"},
		{Name: "sequence_id", Type: field.TypeInt64},
		{Name: "position", Type: field.TypeFloat64, Default: 65536},
		{Name: "start_date", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "target_date", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "archived_at", Type: field.TypeTime, Nullable: true},
		{Name: "is_draft", Type: field.TypeBool, Default: false},
		{Name: "estimate", Type: field.TypeFloat64, Nullable: true},
		{Name: "type_name", Type: field.TypeString, Default: ""},
		{Name: "version", Type: field.TypeInt64, Default: 1},
		{Name: "estimate_point_id", Type: field.TypeUUID, Nullable: true},
		{Name: "requirement_type", Type: field.TypeString, Nullable: true},
		{Name: "story_role", Type: field.TypeString, Default: ""},
		{Name: "story_goal", Type: field.TypeString, Default: ""},
		{Name: "story_benefit", Type: field.TypeString, Default: ""},
		{Name: "acceptance_criteria", Type: field.TypeJSON},
		{Name: "activity_id", Type: field.TypeUUID, Nullable: true},
		{Name: "map_position", Type: field.TypeFloat64, Default: 1024},
		{Name: "estimated_minutes", Type: field.TypeInt, Nullable: true},
		{Name: "remaining_minutes", Type: field.TypeInt, Nullable: true},
		{Name: "required_skills", Type: field.TypeJSON},
		{Name: "allocation_weights", Type: field.TypeJSON},
		{Name: "planning_locked", Type: field.TypeBool, Default: false},
	}
	// WorkItemsTable holds the schema information for the "work_items" table.
	WorkItemsTable = &schema.Table{
		Name:       "work_items",
		Columns:    WorkItemsColumns,
		PrimaryKey: []*schema.Column{WorkItemsColumns[0]},
	}
	// WorkItemAssigneesColumns holds the columns for the "work_item_assignees" table.
	WorkItemAssigneesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "work_item_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// WorkItemAssigneesTable holds the schema information for the "work_item_assignees" table.
	WorkItemAssigneesTable = &schema.Table{
		Name:       "work_item_assignees",
		Columns:    WorkItemAssigneesColumns,
		PrimaryKey: []*schema.Column{WorkItemAssigneesColumns[0]},
	}
	// WorkItemLabelsColumns holds the columns for the "work_item_labels" table.
	WorkItemLabelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "work_item_id", Type: field.TypeUUID},
		{Name: "label_id", Type: field.TypeUUID},
	}
	// WorkItemLabelsTable holds the schema information for the "work_item_labels" table.
	WorkItemLabelsTable = &schema.Table{
		Name:       "work_item_labels",
		Columns:    WorkItemLabelsColumns,
		PrimaryKey: []*schema.Column{WorkItemLabelsColumns[0]},
	}
	// WorkItemLinksColumns holds the columns for the "work_item_links" table.
	WorkItemLinksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "work_item_id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "url", Type: field.TypeString},
		{Name: "created_by", Type: field.TypeUUID},
	}
	// WorkItemLinksTable holds the schema information for the "work_item_links" table.
	WorkItemLinksTable = &schema.Table{
		Name:       "work_item_links",
		Columns:    WorkItemLinksColumns,
		PrimaryKey: []*schema.Column{WorkItemLinksColumns[0]},
	}
	// WorkItemRelationsColumns holds the columns for the "work_item_relations" table.
	WorkItemRelationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "source_id", Type: field.TypeUUID},
		{Name: "target_id", Type: field.TypeUUID},
		{Name: "relation_type", Type: field.TypeString},
	}
	// WorkItemRelationsTable holds the schema information for the "work_item_relations" table.
	WorkItemRelationsTable = &schema.Table{
		Name:       "work_item_relations",
		Columns:    WorkItemRelationsColumns,
		PrimaryKey: []*schema.Column{WorkItemRelationsColumns[0]},
	}
	// WorkItemSubscribersColumns holds the columns for the "work_item_subscribers" table.
	WorkItemSubscribersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "work_item_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// WorkItemSubscribersTable holds the schema information for the "work_item_subscribers" table.
	WorkItemSubscribersTable = &schema.Table{
		Name:       "work_item_subscribers",
		Columns:    WorkItemSubscribersColumns,
		PrimaryKey: []*schema.Column{WorkItemSubscribersColumns[0]},
	}
	// WorkItemVersionsColumns holds the columns for the "work_item_versions" table.
	WorkItemVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "work_item_id", Type: field.TypeUUID},
		{Name: "saved_by", Type: field.TypeUUID},
		{Name: "version", Type: field.TypeInt64},
		{Name: "snapshot", Type: field.TypeJSON},
	}
	// WorkItemVersionsTable holds the schema information for the "work_item_versions" table.
	WorkItemVersionsTable = &schema.Table{
		Name:       "work_item_versions",
		Columns:    WorkItemVersionsColumns,
		PrimaryKey: []*schema.Column{WorkItemVersionsColumns[0]},
	}
	// WorkspacesColumns holds the columns for the "workspaces" table.
	WorkspacesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString},
		{Name: "owner_id", Type: field.TypeUUID},
		{Name: "timezone", Type: field.TypeString, Default: "UTC"},
		{Name: "logo_url", Type: field.TypeString, Default: ""},
		{Name: "description", Type: field.TypeString, Default: ""},
	}
	// WorkspacesTable holds the schema information for the "workspaces" table.
	WorkspacesTable = &schema.Table{
		Name:       "workspaces",
		Columns:    WorkspacesColumns,
		PrimaryKey: []*schema.Column{WorkspacesColumns[0]},
	}
	// WorkspaceMembersColumns holds the columns for the "workspace_members" table.
	WorkspaceMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "role", Type: field.TypeInt, Default: 15},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// WorkspaceMembersTable holds the schema information for the "workspace_members" table.
	WorkspaceMembersTable = &schema.Table{
		Name:       "workspace_members",
		Columns:    WorkspaceMembersColumns,
		PrimaryKey: []*schema.Column{WorkspaceMembersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APITokensTable,
		ActivitiesTable,
		AuthChallengesTable,
		AuthRateLimitsTable,
		CommentsTable,
		CyclesTable,
		CycleItemsTable,
		EstimatesTable,
		EstimatePointsTable,
		ExportsTable,
		FavoritesTable,
		FileAssetsTable,
		InstancesTable,
		IntakeItemsTable,
		InvitationsTable,
		LabelsTable,
		ModulesTable,
		ModuleItemsTable,
		ModuleLinksTable,
		ModuleMembersTable,
		NotificationsTable,
		OauthAccountsTable,
		OutboxEventsTable,
		PagesTable,
		PageCommentsTable,
		PageVersionsTable,
		PreferencesTable,
		ProjectsTable,
		ProjectMembersTable,
		PublicSitesTable,
		PublicVotesTable,
		ReactionsTable,
		RecentVisitsTable,
		SavedAnalysesTable,
		SavedViewsTable,
		SessionsTable,
		StatesTable,
		StickiesTable,
		UsersTable,
		WebhooksTable,
		WebhookDeliveriesTable,
		WorkItemsTable,
		WorkItemAssigneesTable,
		WorkItemLabelsTable,
		WorkItemLinksTable,
		WorkItemRelationsTable,
		WorkItemSubscribersTable,
		WorkItemVersionsTable,
		WorkspacesTable,
		WorkspaceMembersTable,
	}
)

func init() {
	APITokensTable.Annotation = &entsql.Annotation{
		Table: "api_tokens",
	}
	ActivitiesTable.Annotation = &entsql.Annotation{
		Table: "activities",
	}
	AuthChallengesTable.Annotation = &entsql.Annotation{
		Table: "auth_challenges",
	}
	AuthRateLimitsTable.Annotation = &entsql.Annotation{
		Table: "auth_rate_limits",
	}
	CommentsTable.Annotation = &entsql.Annotation{
		Table: "comments",
	}
	CyclesTable.Annotation = &entsql.Annotation{
		Table: "cycles",
	}
	CycleItemsTable.Annotation = &entsql.Annotation{
		Table: "cycle_items",
	}
	EstimatesTable.Annotation = &entsql.Annotation{
		Table: "estimates",
	}
	EstimatePointsTable.Annotation = &entsql.Annotation{
		Table: "estimate_points",
	}
	ExportsTable.Annotation = &entsql.Annotation{
		Table: "exports",
	}
	FavoritesTable.Annotation = &entsql.Annotation{
		Table: "favorites",
	}
	FileAssetsTable.Annotation = &entsql.Annotation{
		Table: "file_assets",
	}
	InstancesTable.Annotation = &entsql.Annotation{
		Table: "instances",
	}
	IntakeItemsTable.Annotation = &entsql.Annotation{
		Table: "intake_items",
	}
	InvitationsTable.Annotation = &entsql.Annotation{
		Table: "invitations",
	}
	LabelsTable.Annotation = &entsql.Annotation{
		Table: "labels",
	}
	ModulesTable.Annotation = &entsql.Annotation{
		Table: "modules",
	}
	ModuleItemsTable.Annotation = &entsql.Annotation{
		Table: "module_items",
	}
	ModuleLinksTable.Annotation = &entsql.Annotation{
		Table: "module_links",
	}
	ModuleMembersTable.Annotation = &entsql.Annotation{
		Table: "module_members",
	}
	NotificationsTable.Annotation = &entsql.Annotation{
		Table: "notifications",
	}
	OauthAccountsTable.Annotation = &entsql.Annotation{
		Table: "oauth_accounts",
	}
	OutboxEventsTable.Annotation = &entsql.Annotation{
		Table: "outbox_events",
	}
	PagesTable.Annotation = &entsql.Annotation{
		Table: "pages",
	}
	PageCommentsTable.Annotation = &entsql.Annotation{
		Table: "page_comments",
	}
	PageVersionsTable.Annotation = &entsql.Annotation{
		Table: "page_versions",
	}
	PreferencesTable.Annotation = &entsql.Annotation{
		Table: "preferences",
	}
	ProjectsTable.Annotation = &entsql.Annotation{
		Table: "projects",
	}
	ProjectMembersTable.Annotation = &entsql.Annotation{
		Table: "project_members",
	}
	PublicSitesTable.Annotation = &entsql.Annotation{
		Table: "public_sites",
	}
	PublicVotesTable.Annotation = &entsql.Annotation{
		Table: "public_votes",
	}
	ReactionsTable.Annotation = &entsql.Annotation{
		Table: "reactions",
	}
	RecentVisitsTable.Annotation = &entsql.Annotation{
		Table: "recent_visits",
	}
	SavedAnalysesTable.Annotation = &entsql.Annotation{
		Table: "saved_analyses",
	}
	SavedViewsTable.Annotation = &entsql.Annotation{
		Table: "saved_views",
	}
	SessionsTable.Annotation = &entsql.Annotation{
		Table: "sessions",
	}
	StatesTable.Annotation = &entsql.Annotation{
		Table: "states",
	}
	StickiesTable.Annotation = &entsql.Annotation{
		Table: "stickies",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
	WebhooksTable.Annotation = &entsql.Annotation{
		Table: "webhooks",
	}
	WebhookDeliveriesTable.Annotation = &entsql.Annotation{
		Table: "webhook_deliveries",
	}
	WorkItemsTable.Annotation = &entsql.Annotation{
		Table: "work_items",
	}
	WorkItemAssigneesTable.Annotation = &entsql.Annotation{
		Table: "work_item_assignees",
	}
	WorkItemLabelsTable.Annotation = &entsql.Annotation{
		Table: "work_item_labels",
	}
	WorkItemLinksTable.Annotation = &entsql.Annotation{
		Table: "work_item_links",
	}
	WorkItemRelationsTable.Annotation = &entsql.Annotation{
		Table: "work_item_relations",
	}
	WorkItemSubscribersTable.Annotation = &entsql.Annotation{
		Table: "work_item_subscribers",
	}
	WorkItemVersionsTable.Annotation = &entsql.Annotation{
		Table: "work_item_versions",
	}
	WorkspacesTable.Annotation = &entsql.Annotation{
		Table: "workspaces",
	}
	WorkspaceMembersTable.Annotation = &entsql.Annotation{
		Table: "workspace_members",
	}
}
