// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"my-jira/apps/api/ent/cycleitem"
	"my-jira/apps/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CycleItemUpdate is the builder for updating CycleItem entities.
type CycleItemUpdate struct {
	config
	hooks    []Hook
	mutation *CycleItemMutation
}

// Where appends a list predicates to the CycleItemUpdate builder.
func (_u *CycleItemUpdate) Where(ps ...predicate.CycleItem) *CycleItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CycleItemUpdate) SetUpdatedAt(v time.Time) *CycleItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CycleItemUpdate) SetDeletedAt(v time.Time) *CycleItemUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CycleItemUpdate) SetNillableDeletedAt(v *time.Time) *CycleItemUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CycleItemUpdate) ClearDeletedAt() *CycleItemUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *CycleItemUpdate) SetWorkspaceID(v uuid.UUID) *CycleItemUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *CycleItemUpdate) SetNillableWorkspaceID(v *uuid.UUID) *CycleItemUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *CycleItemUpdate) SetProjectID(v uuid.UUID) *CycleItemUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *CycleItemUpdate) SetNillableProjectID(v *uuid.UUID) *CycleItemUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetCycleID sets the "cycle_id" field.
func (_u *CycleItemUpdate) SetCycleID(v uuid.UUID) *CycleItemUpdate {
	_u.mutation.SetCycleID(v)
	return _u
}

// SetNillableCycleID sets the "cycle_id" field if the given value is not nil.
func (_u *CycleItemUpdate) SetNillableCycleID(v *uuid.UUID) *CycleItemUpdate {
	if v != nil {
		_u.SetCycleID(*v)
	}
	return _u
}

// SetWorkItemID sets the "work_item_id" field.
func (_u *CycleItemUpdate) SetWorkItemID(v uuid.UUID) *CycleItemUpdate {
	_u.mutation.SetWorkItemID(v)
	return _u
}

// SetNillableWorkItemID sets the "work_item_id" field if the given value is not nil.
func (_u *CycleItemUpdate) SetNillableWorkItemID(v *uuid.UUID) *CycleItemUpdate {
	if v != nil {
		_u.SetWorkItemID(*v)
	}
	return _u
}

// Mutation returns the CycleItemMutation object of the builder.
func (_u *CycleItemUpdate) Mutation() *CycleItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CycleItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CycleItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CycleItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CycleItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CycleItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cycleitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *CycleItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(cycleitem.Table, cycleitem.Columns, sqlgraph.NewFieldSpec(cycleitem.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cycleitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(cycleitem.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(cycleitem.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(cycleitem.FieldWorkspaceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(cycleitem.FieldProjectID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.CycleID(); ok {
		_spec.SetField(cycleitem.FieldCycleID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.WorkItemID(); ok {
		_spec.SetField(cycleitem.FieldWorkItemID, field.TypeUUID, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cycleitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CycleItemUpdateOne is the builder for updating a single CycleItem entity.
type CycleItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CycleItemMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CycleItemUpdateOne) SetUpdatedAt(v time.Time) *CycleItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CycleItemUpdateOne) SetDeletedAt(v time.Time) *CycleItemUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CycleItemUpdateOne) SetNillableDeletedAt(v *time.Time) *CycleItemUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CycleItemUpdateOne) ClearDeletedAt() *CycleItemUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *CycleItemUpdateOne) SetWorkspaceID(v uuid.UUID) *CycleItemUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *CycleItemUpdateOne) SetNillableWorkspaceID(v *uuid.UUID) *CycleItemUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *CycleItemUpdateOne) SetProjectID(v uuid.UUID) *CycleItemUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *CycleItemUpdateOne) SetNillableProjectID(v *uuid.UUID) *CycleItemUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetCycleID sets the "cycle_id" field.
func (_u *CycleItemUpdateOne) SetCycleID(v uuid.UUID) *CycleItemUpdateOne {
	_u.mutation.SetCycleID(v)
	return _u
}

// SetNillableCycleID sets the "cycle_id" field if the given value is not nil.
func (_u *CycleItemUpdateOne) SetNillableCycleID(v *uuid.UUID) *CycleItemUpdateOne {
	if v != nil {
		_u.SetCycleID(*v)
	}
	return _u
}

// SetWorkItemID sets the "work_item_id" field.
func (_u *CycleItemUpdateOne) SetWorkItemID(v uuid.UUID) *CycleItemUpdateOne {
	_u.mutation.SetWorkItemID(v)
	return _u
}

// SetNillableWorkItemID sets the "work_item_id" field if the given value is not nil.
func (_u *CycleItemUpdateOne) SetNillableWorkItemID(v *uuid.UUID) *CycleItemUpdateOne {
	if v != nil {
		_u.SetWorkItemID(*v)
	}
	return _u
}

// Mutation returns the CycleItemMutation object of the builder.
func (_u *CycleItemUpdateOne) Mutation() *CycleItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the CycleItemUpdate builder.
func (_u *CycleItemUpdateOne) Where(ps ...predicate.CycleItem) *CycleItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CycleItemUpdateOne) Select(field string, fields ...string) *CycleItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CycleItem entity.
func (_u *CycleItemUpdateOne) Save(ctx context.Context) (*CycleItem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CycleItemUpdateOne) SaveX(ctx context.Context) *CycleItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CycleItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CycleItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CycleItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cycleitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *CycleItemUpdateOne) sqlSave(ctx context.Context) (_node *CycleItem, err error) {
	_spec := sqlgraph.NewUpdateSpec(cycleitem.Table, cycleitem.Columns, sqlgraph.NewFieldSpec(cycleitem.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CycleItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cycleitem.FieldID)
		for _, f := range fields {
			if !cycleitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cycleitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cycleitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(cycleitem.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(cycleitem.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(cycleitem.FieldWorkspaceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(cycleitem.FieldProjectID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.CycleID(); ok {
		_spec.SetField(cycleitem.FieldCycleID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.WorkItemID(); ok {
		_spec.SetField(cycleitem.FieldWorkItemID, field.TypeUUID, value)
	}
	_node = &CycleItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cycleitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
