// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"my-jira/apps/api/ent/favorite"
	"my-jira/apps/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FavoriteUpdate is the builder for updating Favorite entities.
type FavoriteUpdate struct {
	config
	hooks    []Hook
	mutation *FavoriteMutation
}

// Where appends a list predicates to the FavoriteUpdate builder.
func (_u *FavoriteUpdate) Where(ps ...predicate.Favorite) *FavoriteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FavoriteUpdate) SetUpdatedAt(v time.Time) *FavoriteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FavoriteUpdate) SetDeletedAt(v time.Time) *FavoriteUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FavoriteUpdate) SetNillableDeletedAt(v *time.Time) *FavoriteUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FavoriteUpdate) ClearDeletedAt() *FavoriteUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *FavoriteUpdate) SetWorkspaceID(v uuid.UUID) *FavoriteUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *FavoriteUpdate) SetNillableWorkspaceID(v *uuid.UUID) *FavoriteUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *FavoriteUpdate) SetUserID(v uuid.UUID) *FavoriteUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FavoriteUpdate) SetNillableUserID(v *uuid.UUID) *FavoriteUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *FavoriteUpdate) SetEntityType(v string) *FavoriteUpdate {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *FavoriteUpdate) SetNillableEntityType(v *string) *FavoriteUpdate {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *FavoriteUpdate) SetEntityID(v uuid.UUID) *FavoriteUpdate {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *FavoriteUpdate) SetNillableEntityID(v *uuid.UUID) *FavoriteUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *FavoriteUpdate) SetPosition(v float64) *FavoriteUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *FavoriteUpdate) SetNillablePosition(v *float64) *FavoriteUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *FavoriteUpdate) AddPosition(v float64) *FavoriteUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// Mutation returns the FavoriteMutation object of the builder.
func (_u *FavoriteUpdate) Mutation() *FavoriteMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FavoriteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FavoriteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FavoriteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FavoriteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FavoriteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := favorite.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *FavoriteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(favorite.Table, favorite.Columns, sqlgraph.NewFieldSpec(favorite.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(favorite.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(favorite.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(favorite.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(favorite.FieldWorkspaceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(favorite.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(favorite.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(favorite.FieldEntityID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(favorite.FieldPosition, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(favorite.FieldPosition, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{favorite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FavoriteUpdateOne is the builder for updating a single Favorite entity.
type FavoriteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FavoriteMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FavoriteUpdateOne) SetUpdatedAt(v time.Time) *FavoriteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FavoriteUpdateOne) SetDeletedAt(v time.Time) *FavoriteUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FavoriteUpdateOne) SetNillableDeletedAt(v *time.Time) *FavoriteUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FavoriteUpdateOne) ClearDeletedAt() *FavoriteUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *FavoriteUpdateOne) SetWorkspaceID(v uuid.UUID) *FavoriteUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *FavoriteUpdateOne) SetNillableWorkspaceID(v *uuid.UUID) *FavoriteUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *FavoriteUpdateOne) SetUserID(v uuid.UUID) *FavoriteUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FavoriteUpdateOne) SetNillableUserID(v *uuid.UUID) *FavoriteUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *FavoriteUpdateOne) SetEntityType(v string) *FavoriteUpdateOne {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *FavoriteUpdateOne) SetNillableEntityType(v *string) *FavoriteUpdateOne {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *FavoriteUpdateOne) SetEntityID(v uuid.UUID) *FavoriteUpdateOne {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *FavoriteUpdateOne) SetNillableEntityID(v *uuid.UUID) *FavoriteUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *FavoriteUpdateOne) SetPosition(v float64) *FavoriteUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *FavoriteUpdateOne) SetNillablePosition(v *float64) *FavoriteUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *FavoriteUpdateOne) AddPosition(v float64) *FavoriteUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// Mutation returns the FavoriteMutation object of the builder.
func (_u *FavoriteUpdateOne) Mutation() *FavoriteMutation {
	return _u.mutation
}

// Where appends a list predicates to the FavoriteUpdate builder.
func (_u *FavoriteUpdateOne) Where(ps ...predicate.Favorite) *FavoriteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FavoriteUpdateOne) Select(field string, fields ...string) *FavoriteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Favorite entity.
func (_u *FavoriteUpdateOne) Save(ctx context.Context) (*Favorite, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FavoriteUpdateOne) SaveX(ctx context.Context) *Favorite {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FavoriteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FavoriteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FavoriteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := favorite.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *FavoriteUpdateOne) sqlSave(ctx context.Context) (_node *Favorite, err error) {
	_spec := sqlgraph.NewUpdateSpec(favorite.Table, favorite.Columns, sqlgraph.NewFieldSpec(favorite.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Favorite.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, favorite.FieldID)
		for _, f := range fields {
			if !favorite.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != favorite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(favorite.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(favorite.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(favorite.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(favorite.FieldWorkspaceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(favorite.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(favorite.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(favorite.FieldEntityID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(favorite.FieldPosition, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(favorite.FieldPosition, field.TypeFloat64, value)
	}
	_node = &Favorite{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{favorite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
