// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"my-jira/apps/api/ent/moduleitem"
	"my-jira/apps/api/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ModuleItemDelete is the builder for deleting a ModuleItem entity.
type ModuleItemDelete struct {
	config
	hooks    []Hook
	mutation *ModuleItemMutation
}

// Where appends a list predicates to the ModuleItemDelete builder.
func (_d *ModuleItemDelete) Where(ps ...predicate.ModuleItem) *ModuleItemDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ModuleItemDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModuleItemDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ModuleItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(moduleitem.Table, sqlgraph.NewFieldSpec(moduleitem.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ModuleItemDeleteOne is the builder for deleting a single ModuleItem entity.
type ModuleItemDeleteOne struct {
	_d *ModuleItemDelete
}

// Where appends a list predicates to the ModuleItemDelete builder.
func (_d *ModuleItemDeleteOne) Where(ps ...predicate.ModuleItem) *ModuleItemDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ModuleItemDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{moduleitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModuleItemDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
