// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"my-jira/apps/api/ent/outboxevent"
	"my-jira/apps/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OutboxEventUpdate is the builder for updating OutboxEvent entities.
type OutboxEventUpdate struct {
	config
	hooks    []Hook
	mutation *OutboxEventMutation
}

// Where appends a list predicates to the OutboxEventUpdate builder.
func (_u *OutboxEventUpdate) Where(ps ...predicate.OutboxEvent) *OutboxEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OutboxEventUpdate) SetUpdatedAt(v time.Time) *OutboxEventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OutboxEventUpdate) SetDeletedAt(v time.Time) *OutboxEventUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableDeletedAt(v *time.Time) *OutboxEventUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *OutboxEventUpdate) ClearDeletedAt() *OutboxEventUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTopic sets the "topic" field.
func (_u *OutboxEventUpdate) SetTopic(v string) *OutboxEventUpdate {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableTopic(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *OutboxEventUpdate) SetPayload(v map[string]interface{}) *OutboxEventUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetDeduplicationKey sets the "deduplication_key" field.
func (_u *OutboxEventUpdate) SetDeduplicationKey(v string) *OutboxEventUpdate {
	_u.mutation.SetDeduplicationKey(v)
	return _u
}

// SetNillableDeduplicationKey sets the "deduplication_key" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableDeduplicationKey(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetDeduplicationKey(*v)
	}
	return _u
}

// SetDispatchedAt sets the "dispatched_at" field.
func (_u *OutboxEventUpdate) SetDispatchedAt(v time.Time) *OutboxEventUpdate {
	_u.mutation.SetDispatchedAt(v)
	return _u
}

// SetNillableDispatchedAt sets the "dispatched_at" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableDispatchedAt(v *time.Time) *OutboxEventUpdate {
	if v != nil {
		_u.SetDispatchedAt(*v)
	}
	return _u
}

// ClearDispatchedAt clears the value of the "dispatched_at" field.
func (_u *OutboxEventUpdate) ClearDispatchedAt() *OutboxEventUpdate {
	_u.mutation.ClearDispatchedAt()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *OutboxEventUpdate) SetAttempts(v int) *OutboxEventUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableAttempts(v *int) *OutboxEventUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *OutboxEventUpdate) AddAttempts(v int) *OutboxEventUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *OutboxEventUpdate) SetLastError(v string) *OutboxEventUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableLastError(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// Mutation returns the OutboxEventMutation object of the builder.
func (_u *OutboxEventUpdate) Mutation() *OutboxEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OutboxEventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutboxEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OutboxEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutboxEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OutboxEventUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := outboxevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *OutboxEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(outboxevent.Table, outboxevent.Columns, sqlgraph.NewFieldSpec(outboxevent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(outboxevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(outboxevent.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(outboxevent.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(outboxevent.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(outboxevent.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.DeduplicationKey(); ok {
		_spec.SetField(outboxevent.FieldDeduplicationKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DispatchedAt(); ok {
		_spec.SetField(outboxevent.FieldDispatchedAt, field.TypeTime, value)
	}
	if _u.mutation.DispatchedAtCleared() {
		_spec.ClearField(outboxevent.FieldDispatchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(outboxevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(outboxevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(outboxevent.FieldLastError, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outboxevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OutboxEventUpdateOne is the builder for updating a single OutboxEvent entity.
type OutboxEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OutboxEventMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OutboxEventUpdateOne) SetUpdatedAt(v time.Time) *OutboxEventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OutboxEventUpdateOne) SetDeletedAt(v time.Time) *OutboxEventUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableDeletedAt(v *time.Time) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *OutboxEventUpdateOne) ClearDeletedAt() *OutboxEventUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTopic sets the "topic" field.
func (_u *OutboxEventUpdateOne) SetTopic(v string) *OutboxEventUpdateOne {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableTopic(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *OutboxEventUpdateOne) SetPayload(v map[string]interface{}) *OutboxEventUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetDeduplicationKey sets the "deduplication_key" field.
func (_u *OutboxEventUpdateOne) SetDeduplicationKey(v string) *OutboxEventUpdateOne {
	_u.mutation.SetDeduplicationKey(v)
	return _u
}

// SetNillableDeduplicationKey sets the "deduplication_key" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableDeduplicationKey(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetDeduplicationKey(*v)
	}
	return _u
}

// SetDispatchedAt sets the "dispatched_at" field.
func (_u *OutboxEventUpdateOne) SetDispatchedAt(v time.Time) *OutboxEventUpdateOne {
	_u.mutation.SetDispatchedAt(v)
	return _u
}

// SetNillableDispatchedAt sets the "dispatched_at" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableDispatchedAt(v *time.Time) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetDispatchedAt(*v)
	}
	return _u
}

// ClearDispatchedAt clears the value of the "dispatched_at" field.
func (_u *OutboxEventUpdateOne) ClearDispatchedAt() *OutboxEventUpdateOne {
	_u.mutation.ClearDispatchedAt()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *OutboxEventUpdateOne) SetAttempts(v int) *OutboxEventUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableAttempts(v *int) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *OutboxEventUpdateOne) AddAttempts(v int) *OutboxEventUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *OutboxEventUpdateOne) SetLastError(v string) *OutboxEventUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableLastError(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// Mutation returns the OutboxEventMutation object of the builder.
func (_u *OutboxEventUpdateOne) Mutation() *OutboxEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the OutboxEventUpdate builder.
func (_u *OutboxEventUpdateOne) Where(ps ...predicate.OutboxEvent) *OutboxEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OutboxEventUpdateOne) Select(field string, fields ...string) *OutboxEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OutboxEvent entity.
func (_u *OutboxEventUpdateOne) Save(ctx context.Context) (*OutboxEvent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutboxEventUpdateOne) SaveX(ctx context.Context) *OutboxEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OutboxEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutboxEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OutboxEventUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := outboxevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *OutboxEventUpdateOne) sqlSave(ctx context.Context) (_node *OutboxEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(outboxevent.Table, outboxevent.Columns, sqlgraph.NewFieldSpec(outboxevent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OutboxEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, outboxevent.FieldID)
		for _, f := range fields {
			if !outboxevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != outboxevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(outboxevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(outboxevent.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(outboxevent.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(outboxevent.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(outboxevent.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.DeduplicationKey(); ok {
		_spec.SetField(outboxevent.FieldDeduplicationKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DispatchedAt(); ok {
		_spec.SetField(outboxevent.FieldDispatchedAt, field.TypeTime, value)
	}
	if _u.mutation.DispatchedAtCleared() {
		_spec.ClearField(outboxevent.FieldDispatchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(outboxevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(outboxevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(outboxevent.FieldLastError, field.TypeString, value)
	}
	_node = &OutboxEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outboxevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
