// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"my-jira/apps/api/ent/savedanalysis"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SavedAnalysisCreate is the builder for creating a SavedAnalysis entity.
type SavedAnalysisCreate struct {
	config
	mutation *SavedAnalysisMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SavedAnalysisCreate) SetCreatedAt(v time.Time) *SavedAnalysisCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SavedAnalysisCreate) SetNillableCreatedAt(v *time.Time) *SavedAnalysisCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SavedAnalysisCreate) SetUpdatedAt(v time.Time) *SavedAnalysisCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SavedAnalysisCreate) SetNillableUpdatedAt(v *time.Time) *SavedAnalysisCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SavedAnalysisCreate) SetDeletedAt(v time.Time) *SavedAnalysisCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SavedAnalysisCreate) SetNillableDeletedAt(v *time.Time) *SavedAnalysisCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *SavedAnalysisCreate) SetWorkspaceID(v uuid.UUID) *SavedAnalysisCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *SavedAnalysisCreate) SetName(v string) *SavedAnalysisCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SavedAnalysisCreate) SetDescription(v string) *SavedAnalysisCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SavedAnalysisCreate) SetNillableDescription(v *string) *SavedAnalysisCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetOwnerID sets the "owner_id" field.
func (_c *SavedAnalysisCreate) SetOwnerID(v uuid.UUID) *SavedAnalysisCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetQuery sets the "query" field.
func (_c *SavedAnalysisCreate) SetQuery(v map[string]interface{}) *SavedAnalysisCreate {
	_c.mutation.SetQuery(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SavedAnalysisCreate) SetID(v uuid.UUID) *SavedAnalysisCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SavedAnalysisCreate) SetNillableID(v *uuid.UUID) *SavedAnalysisCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SavedAnalysisMutation object of the builder.
func (_c *SavedAnalysisCreate) Mutation() *SavedAnalysisMutation {
	return _c.mutation
}

// Save creates the SavedAnalysis in the database.
func (_c *SavedAnalysisCreate) Save(ctx context.Context) (*SavedAnalysis, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SavedAnalysisCreate) SaveX(ctx context.Context) *SavedAnalysis {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SavedAnalysisCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SavedAnalysisCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SavedAnalysisCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := savedanalysis.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := savedanalysis.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := savedanalysis.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Query(); !ok {
		v := savedanalysis.DefaultQuery
		_c.mutation.SetQuery(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := savedanalysis.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SavedAnalysisCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SavedAnalysis.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SavedAnalysis.updated_at"`)}
	}
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "SavedAnalysis.workspace_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SavedAnalysis.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := savedanalysis.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SavedAnalysis.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "SavedAnalysis.description"`)}
	}
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "SavedAnalysis.owner_id"`)}
	}
	if _, ok := _c.mutation.Query(); !ok {
		return &ValidationError{Name: "query", err: errors.New(`ent: missing required field "SavedAnalysis.query"`)}
	}
	return nil
}

func (_c *SavedAnalysisCreate) sqlSave(ctx context.Context) (*SavedAnalysis, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SavedAnalysisCreate) createSpec() (*SavedAnalysis, *sqlgraph.CreateSpec) {
	var (
		_node = &SavedAnalysis{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(savedanalysis.Table, sqlgraph.NewFieldSpec(savedanalysis.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(savedanalysis.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(savedanalysis.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(savedanalysis.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.WorkspaceID(); ok {
		_spec.SetField(savedanalysis.FieldWorkspaceID, field.TypeUUID, value)
		_node.WorkspaceID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(savedanalysis.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(savedanalysis.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.OwnerID(); ok {
		_spec.SetField(savedanalysis.FieldOwnerID, field.TypeUUID, value)
		_node.OwnerID = value
	}
	if value, ok := _c.mutation.Query(); ok {
		_spec.SetField(savedanalysis.FieldQuery, field.TypeJSON, value)
		_node.Query = value
	}
	return _node, _spec
}

// SavedAnalysisCreateBulk is the builder for creating many SavedAnalysis entities in bulk.
type SavedAnalysisCreateBulk struct {
	config
	err      error
	builders []*SavedAnalysisCreate
}

// Save creates the SavedAnalysis entities in the database.
func (_c *SavedAnalysisCreateBulk) Save(ctx context.Context) ([]*SavedAnalysis, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SavedAnalysis, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SavedAnalysisMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SavedAnalysisCreateBulk) SaveX(ctx context.Context) []*SavedAnalysis {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SavedAnalysisCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SavedAnalysisCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
