// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"my-jira/apps/api/ent/savedview"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SavedViewCreate is the builder for creating a SavedView entity.
type SavedViewCreate struct {
	config
	mutation *SavedViewMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SavedViewCreate) SetCreatedAt(v time.Time) *SavedViewCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SavedViewCreate) SetNillableCreatedAt(v *time.Time) *SavedViewCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SavedViewCreate) SetUpdatedAt(v time.Time) *SavedViewCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SavedViewCreate) SetNillableUpdatedAt(v *time.Time) *SavedViewCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SavedViewCreate) SetDeletedAt(v time.Time) *SavedViewCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SavedViewCreate) SetNillableDeletedAt(v *time.Time) *SavedViewCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *SavedViewCreate) SetWorkspaceID(v uuid.UUID) *SavedViewCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *SavedViewCreate) SetProjectID(v uuid.UUID) *SavedViewCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_c *SavedViewCreate) SetNillableProjectID(v *uuid.UUID) *SavedViewCreate {
	if v != nil {
		_c.SetProjectID(*v)
	}
	return _c
}

// SetOwnerID sets the "owner_id" field.
func (_c *SavedViewCreate) SetOwnerID(v uuid.UUID) *SavedViewCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *SavedViewCreate) SetName(v string) *SavedViewCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SavedViewCreate) SetDescription(v string) *SavedViewCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SavedViewCreate) SetNillableDescription(v *string) *SavedViewCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetLayout sets the "layout" field.
func (_c *SavedViewCreate) SetLayout(v string) *SavedViewCreate {
	_c.mutation.SetLayout(v)
	return _c
}

// SetNillableLayout sets the "layout" field if the given value is not nil.
func (_c *SavedViewCreate) SetNillableLayout(v *string) *SavedViewCreate {
	if v != nil {
		_c.SetLayout(*v)
	}
	return _c
}

// SetFilters sets the "filters" field.
func (_c *SavedViewCreate) SetFilters(v map[string]interface{}) *SavedViewCreate {
	_c.mutation.SetFilters(v)
	return _c
}

// SetDisplay sets the "display" field.
func (_c *SavedViewCreate) SetDisplay(v map[string]interface{}) *SavedViewCreate {
	_c.mutation.SetDisplay(v)
	return _c
}

// SetIsPrivate sets the "is_private" field.
func (_c *SavedViewCreate) SetIsPrivate(v bool) *SavedViewCreate {
	_c.mutation.SetIsPrivate(v)
	return _c
}

// SetNillableIsPrivate sets the "is_private" field if the given value is not nil.
func (_c *SavedViewCreate) SetNillableIsPrivate(v *bool) *SavedViewCreate {
	if v != nil {
		_c.SetIsPrivate(*v)
	}
	return _c
}

// SetPosition sets the "position" field.
func (_c *SavedViewCreate) SetPosition(v float64) *SavedViewCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_c *SavedViewCreate) SetNillablePosition(v *float64) *SavedViewCreate {
	if v != nil {
		_c.SetPosition(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SavedViewCreate) SetID(v uuid.UUID) *SavedViewCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SavedViewCreate) SetNillableID(v *uuid.UUID) *SavedViewCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SavedViewMutation object of the builder.
func (_c *SavedViewCreate) Mutation() *SavedViewMutation {
	return _c.mutation
}

// Save creates the SavedView in the database.
func (_c *SavedViewCreate) Save(ctx context.Context) (*SavedView, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SavedViewCreate) SaveX(ctx context.Context) *SavedView {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SavedViewCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SavedViewCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SavedViewCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := savedview.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := savedview.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := savedview.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Layout(); !ok {
		v := savedview.DefaultLayout
		_c.mutation.SetLayout(v)
	}
	if _, ok := _c.mutation.Filters(); !ok {
		v := savedview.DefaultFilters
		_c.mutation.SetFilters(v)
	}
	if _, ok := _c.mutation.Display(); !ok {
		v := savedview.DefaultDisplay
		_c.mutation.SetDisplay(v)
	}
	if _, ok := _c.mutation.IsPrivate(); !ok {
		v := savedview.DefaultIsPrivate
		_c.mutation.SetIsPrivate(v)
	}
	if _, ok := _c.mutation.Position(); !ok {
		v := savedview.DefaultPosition
		_c.mutation.SetPosition(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := savedview.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SavedViewCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SavedView.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SavedView.updated_at"`)}
	}
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "SavedView.workspace_id"`)}
	}
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "SavedView.owner_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SavedView.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "SavedView.description"`)}
	}
	if _, ok := _c.mutation.Layout(); !ok {
		return &ValidationError{Name: "layout", err: errors.New(`ent: missing required field "SavedView.layout"`)}
	}
	if _, ok := _c.mutation.Filters(); !ok {
		return &ValidationError{Name: "filters", err: errors.New(`ent: missing required field "SavedView.filters"`)}
	}
	if _, ok := _c.mutation.Display(); !ok {
		return &ValidationError{Name: "display", err: errors.New(`ent: missing required field "SavedView.display"`)}
	}
	if _, ok := _c.mutation.IsPrivate(); !ok {
		return &ValidationError{Name: "is_private", err: errors.New(`ent: missing required field "SavedView.is_private"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "SavedView.position"`)}
	}
	return nil
}

func (_c *SavedViewCreate) sqlSave(ctx context.Context) (*SavedView, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SavedViewCreate) createSpec() (*SavedView, *sqlgraph.CreateSpec) {
	var (
		_node = &SavedView{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(savedview.Table, sqlgraph.NewFieldSpec(savedview.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(savedview.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(savedview.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(savedview.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.WorkspaceID(); ok {
		_spec.SetField(savedview.FieldWorkspaceID, field.TypeUUID, value)
		_node.WorkspaceID = value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(savedview.FieldProjectID, field.TypeUUID, value)
		_node.ProjectID = &value
	}
	if value, ok := _c.mutation.OwnerID(); ok {
		_spec.SetField(savedview.FieldOwnerID, field.TypeUUID, value)
		_node.OwnerID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(savedview.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(savedview.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Layout(); ok {
		_spec.SetField(savedview.FieldLayout, field.TypeString, value)
		_node.Layout = value
	}
	if value, ok := _c.mutation.Filters(); ok {
		_spec.SetField(savedview.FieldFilters, field.TypeJSON, value)
		_node.Filters = value
	}
	if value, ok := _c.mutation.Display(); ok {
		_spec.SetField(savedview.FieldDisplay, field.TypeJSON, value)
		_node.Display = value
	}
	if value, ok := _c.mutation.IsPrivate(); ok {
		_spec.SetField(savedview.FieldIsPrivate, field.TypeBool, value)
		_node.IsPrivate = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(savedview.FieldPosition, field.TypeFloat64, value)
		_node.Position = value
	}
	return _node, _spec
}

// SavedViewCreateBulk is the builder for creating many SavedView entities in bulk.
type SavedViewCreateBulk struct {
	config
	err      error
	builders []*SavedViewCreate
}

// Save creates the SavedView entities in the database.
func (_c *SavedViewCreateBulk) Save(ctx context.Context) ([]*SavedView, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SavedView, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SavedViewMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SavedViewCreateBulk) SaveX(ctx context.Context) []*SavedView {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SavedViewCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SavedViewCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
