// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"my-jira/apps/api/ent/predicate"
	"my-jira/apps/api/ent/savedview"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SavedViewUpdate is the builder for updating SavedView entities.
type SavedViewUpdate struct {
	config
	hooks    []Hook
	mutation *SavedViewMutation
}

// Where appends a list predicates to the SavedViewUpdate builder.
func (_u *SavedViewUpdate) Where(ps ...predicate.SavedView) *SavedViewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SavedViewUpdate) SetUpdatedAt(v time.Time) *SavedViewUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SavedViewUpdate) SetDeletedAt(v time.Time) *SavedViewUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SavedViewUpdate) SetNillableDeletedAt(v *time.Time) *SavedViewUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SavedViewUpdate) ClearDeletedAt() *SavedViewUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *SavedViewUpdate) SetWorkspaceID(v uuid.UUID) *SavedViewUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *SavedViewUpdate) SetNillableWorkspaceID(v *uuid.UUID) *SavedViewUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *SavedViewUpdate) SetProjectID(v uuid.UUID) *SavedViewUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *SavedViewUpdate) SetNillableProjectID(v *uuid.UUID) *SavedViewUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *SavedViewUpdate) ClearProjectID() *SavedViewUpdate {
	_u.mutation.ClearProjectID()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *SavedViewUpdate) SetOwnerID(v uuid.UUID) *SavedViewUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *SavedViewUpdate) SetNillableOwnerID(v *uuid.UUID) *SavedViewUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SavedViewUpdate) SetName(v string) *SavedViewUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SavedViewUpdate) SetNillableName(v *string) *SavedViewUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SavedViewUpdate) SetDescription(v string) *SavedViewUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SavedViewUpdate) SetNillableDescription(v *string) *SavedViewUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetLayout sets the "layout" field.
func (_u *SavedViewUpdate) SetLayout(v string) *SavedViewUpdate {
	_u.mutation.SetLayout(v)
	return _u
}

// SetNillableLayout sets the "layout" field if the given value is not nil.
func (_u *SavedViewUpdate) SetNillableLayout(v *string) *SavedViewUpdate {
	if v != nil {
		_u.SetLayout(*v)
	}
	return _u
}

// SetFilters sets the "filters" field.
func (_u *SavedViewUpdate) SetFilters(v map[string]interface{}) *SavedViewUpdate {
	_u.mutation.SetFilters(v)
	return _u
}

// SetDisplay sets the "display" field.
func (_u *SavedViewUpdate) SetDisplay(v map[string]interface{}) *SavedViewUpdate {
	_u.mutation.SetDisplay(v)
	return _u
}

// SetIsPrivate sets the "is_private" field.
func (_u *SavedViewUpdate) SetIsPrivate(v bool) *SavedViewUpdate {
	_u.mutation.SetIsPrivate(v)
	return _u
}

// SetNillableIsPrivate sets the "is_private" field if the given value is not nil.
func (_u *SavedViewUpdate) SetNillableIsPrivate(v *bool) *SavedViewUpdate {
	if v != nil {
		_u.SetIsPrivate(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *SavedViewUpdate) SetPosition(v float64) *SavedViewUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *SavedViewUpdate) SetNillablePosition(v *float64) *SavedViewUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *SavedViewUpdate) AddPosition(v float64) *SavedViewUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// Mutation returns the SavedViewMutation object of the builder.
func (_u *SavedViewUpdate) Mutation() *SavedViewMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SavedViewUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SavedViewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SavedViewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SavedViewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SavedViewUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := savedview.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SavedViewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(savedview.Table, savedview.Columns, sqlgraph.NewFieldSpec(savedview.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(savedview.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(savedview.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(savedview.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(savedview.FieldWorkspaceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(savedview.FieldProjectID, field.TypeUUID, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(savedview.FieldProjectID, field.TypeUUID)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(savedview.FieldOwnerID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(savedview.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(savedview.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Layout(); ok {
		_spec.SetField(savedview.FieldLayout, field.TypeString, value)
	}
	if value, ok := _u.mutation.Filters(); ok {
		_spec.SetField(savedview.FieldFilters, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Display(); ok {
		_spec.SetField(savedview.FieldDisplay, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.IsPrivate(); ok {
		_spec.SetField(savedview.FieldIsPrivate, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(savedview.FieldPosition, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(savedview.FieldPosition, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{savedview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SavedViewUpdateOne is the builder for updating a single SavedView entity.
type SavedViewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SavedViewMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SavedViewUpdateOne) SetUpdatedAt(v time.Time) *SavedViewUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SavedViewUpdateOne) SetDeletedAt(v time.Time) *SavedViewUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SavedViewUpdateOne) SetNillableDeletedAt(v *time.Time) *SavedViewUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SavedViewUpdateOne) ClearDeletedAt() *SavedViewUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *SavedViewUpdateOne) SetWorkspaceID(v uuid.UUID) *SavedViewUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *SavedViewUpdateOne) SetNillableWorkspaceID(v *uuid.UUID) *SavedViewUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *SavedViewUpdateOne) SetProjectID(v uuid.UUID) *SavedViewUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *SavedViewUpdateOne) SetNillableProjectID(v *uuid.UUID) *SavedViewUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *SavedViewUpdateOne) ClearProjectID() *SavedViewUpdateOne {
	_u.mutation.ClearProjectID()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *SavedViewUpdateOne) SetOwnerID(v uuid.UUID) *SavedViewUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *SavedViewUpdateOne) SetNillableOwnerID(v *uuid.UUID) *SavedViewUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SavedViewUpdateOne) SetName(v string) *SavedViewUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SavedViewUpdateOne) SetNillableName(v *string) *SavedViewUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SavedViewUpdateOne) SetDescription(v string) *SavedViewUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SavedViewUpdateOne) SetNillableDescription(v *string) *SavedViewUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetLayout sets the "layout" field.
func (_u *SavedViewUpdateOne) SetLayout(v string) *SavedViewUpdateOne {
	_u.mutation.SetLayout(v)
	return _u
}

// SetNillableLayout sets the "layout" field if the given value is not nil.
func (_u *SavedViewUpdateOne) SetNillableLayout(v *string) *SavedViewUpdateOne {
	if v != nil {
		_u.SetLayout(*v)
	}
	return _u
}

// SetFilters sets the "filters" field.
func (_u *SavedViewUpdateOne) SetFilters(v map[string]interface{}) *SavedViewUpdateOne {
	_u.mutation.SetFilters(v)
	return _u
}

// SetDisplay sets the "display" field.
func (_u *SavedViewUpdateOne) SetDisplay(v map[string]interface{}) *SavedViewUpdateOne {
	_u.mutation.SetDisplay(v)
	return _u
}

// SetIsPrivate sets the "is_private" field.
func (_u *SavedViewUpdateOne) SetIsPrivate(v bool) *SavedViewUpdateOne {
	_u.mutation.SetIsPrivate(v)
	return _u
}

// SetNillableIsPrivate sets the "is_private" field if the given value is not nil.
func (_u *SavedViewUpdateOne) SetNillableIsPrivate(v *bool) *SavedViewUpdateOne {
	if v != nil {
		_u.SetIsPrivate(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *SavedViewUpdateOne) SetPosition(v float64) *SavedViewUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *SavedViewUpdateOne) SetNillablePosition(v *float64) *SavedViewUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *SavedViewUpdateOne) AddPosition(v float64) *SavedViewUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// Mutation returns the SavedViewMutation object of the builder.
func (_u *SavedViewUpdateOne) Mutation() *SavedViewMutation {
	return _u.mutation
}

// Where appends a list predicates to the SavedViewUpdate builder.
func (_u *SavedViewUpdateOne) Where(ps ...predicate.SavedView) *SavedViewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SavedViewUpdateOne) Select(field string, fields ...string) *SavedViewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SavedView entity.
func (_u *SavedViewUpdateOne) Save(ctx context.Context) (*SavedView, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SavedViewUpdateOne) SaveX(ctx context.Context) *SavedView {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SavedViewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SavedViewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SavedViewUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := savedview.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SavedViewUpdateOne) sqlSave(ctx context.Context) (_node *SavedView, err error) {
	_spec := sqlgraph.NewUpdateSpec(savedview.Table, savedview.Columns, sqlgraph.NewFieldSpec(savedview.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SavedView.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, savedview.FieldID)
		for _, f := range fields {
			if !savedview.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != savedview.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(savedview.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(savedview.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(savedview.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(savedview.FieldWorkspaceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(savedview.FieldProjectID, field.TypeUUID, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(savedview.FieldProjectID, field.TypeUUID)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(savedview.FieldOwnerID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(savedview.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(savedview.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Layout(); ok {
		_spec.SetField(savedview.FieldLayout, field.TypeString, value)
	}
	if value, ok := _u.mutation.Filters(); ok {
		_spec.SetField(savedview.FieldFilters, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Display(); ok {
		_spec.SetField(savedview.FieldDisplay, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.IsPrivate(); ok {
		_spec.SetField(savedview.FieldIsPrivate, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(savedview.FieldPosition, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(savedview.FieldPosition, field.TypeFloat64, value)
	}
	_node = &SavedView{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{savedview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
