// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"sync"

	"entgo.io/ent/dialect"
)

// Tx is a transactional client that is created by calling Client.Tx().
type Tx struct {
	config
	// APIToken is the client for interacting with the APIToken builders.
	APIToken *APITokenClient
	// Activity is the client for interacting with the Activity builders.
	Activity *ActivityClient
	// AuthChallenge is the client for interacting with the AuthChallenge builders.
	AuthChallenge *AuthChallengeClient
	// AuthRateLimit is the client for interacting with the AuthRateLimit builders.
	AuthRateLimit *AuthRateLimitClient
	// Comment is the client for interacting with the Comment builders.
	Comment *CommentClient
	// Cycle is the client for interacting with the Cycle builders.
	Cycle *CycleClient
	// CycleItem is the client for interacting with the CycleItem builders.
	CycleItem *CycleItemClient
	// Estimate is the client for interacting with the Estimate builders.
	Estimate *EstimateClient
	// EstimatePoint is the client for interacting with the EstimatePoint builders.
	EstimatePoint *EstimatePointClient
	// Export is the client for interacting with the Export builders.
	Export *ExportClient
	// Favorite is the client for interacting with the Favorite builders.
	Favorite *FavoriteClient
	// FileAsset is the client for interacting with the FileAsset builders.
	FileAsset *FileAssetClient
	// Instance is the client for interacting with the Instance builders.
	Instance *InstanceClient
	// IntakeItem is the client for interacting with the IntakeItem builders.
	IntakeItem *IntakeItemClient
	// Invitation is the client for interacting with the Invitation builders.
	Invitation *InvitationClient
	// Label is the client for interacting with the Label builders.
	Label *LabelClient
	// Module is the client for interacting with the Module builders.
	Module *ModuleClient
	// ModuleItem is the client for interacting with the ModuleItem builders.
	ModuleItem *ModuleItemClient
	// ModuleLink is the client for interacting with the ModuleLink builders.
	ModuleLink *ModuleLinkClient
	// ModuleMember is the client for interacting with the ModuleMember builders.
	ModuleMember *ModuleMemberClient
	// Notification is the client for interacting with the Notification builders.
	Notification *NotificationClient
	// OAuthAccount is the client for interacting with the OAuthAccount builders.
	OAuthAccount *OAuthAccountClient
	// OutboxEvent is the client for interacting with the OutboxEvent builders.
	OutboxEvent *OutboxEventClient
	// Page is the client for interacting with the Page builders.
	Page *PageClient
	// PageComment is the client for interacting with the PageComment builders.
	PageComment *PageCommentClient
	// PageVersion is the client for interacting with the PageVersion builders.
	PageVersion *PageVersionClient
	// Preference is the client for interacting with the Preference builders.
	Preference *PreferenceClient
	// Project is the client for interacting with the Project builders.
	Project *ProjectClient
	// ProjectMember is the client for interacting with the ProjectMember builders.
	ProjectMember *ProjectMemberClient
	// PublicSite is the client for interacting with the PublicSite builders.
	PublicSite *PublicSiteClient
	// PublicVote is the client for interacting with the PublicVote builders.
	PublicVote *PublicVoteClient
	// Reaction is the client for interacting with the Reaction builders.
	Reaction *ReactionClient
	// RecentVisit is the client for interacting with the RecentVisit builders.
	RecentVisit *RecentVisitClient
	// SavedAnalysis is the client for interacting with the SavedAnalysis builders.
	SavedAnalysis *SavedAnalysisClient
	// SavedView is the client for interacting with the SavedView builders.
	SavedView *SavedViewClient
	// Session is the client for interacting with the Session builders.
	Session *SessionClient
	// State is the client for interacting with the State builders.
	State *StateClient
	// Sticky is the client for interacting with the Sticky builders.
	Sticky *StickyClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// Webhook is the client for interacting with the Webhook builders.
	Webhook *WebhookClient
	// WebhookDelivery is the client for interacting with the WebhookDelivery builders.
	WebhookDelivery *WebhookDeliveryClient
	// WorkItem is the client for interacting with the WorkItem builders.
	WorkItem *WorkItemClient
	// WorkItemAssignee is the client for interacting with the WorkItemAssignee builders.
	WorkItemAssignee *WorkItemAssigneeClient
	// WorkItemLabel is the client for interacting with the WorkItemLabel builders.
	WorkItemLabel *WorkItemLabelClient
	// WorkItemLink is the client for interacting with the WorkItemLink builders.
	WorkItemLink *WorkItemLinkClient
	// WorkItemRelation is the client for interacting with the WorkItemRelation builders.
	WorkItemRelation *WorkItemRelationClient
	// WorkItemSubscriber is the client for interacting with the WorkItemSubscriber builders.
	WorkItemSubscriber *WorkItemSubscriberClient
	// WorkItemVersion is the client for interacting with the WorkItemVersion builders.
	WorkItemVersion *WorkItemVersionClient
	// Workspace is the client for interacting with the Workspace builders.
	Workspace *WorkspaceClient
	// WorkspaceMember is the client for interacting with the WorkspaceMember builders.
	WorkspaceMember *WorkspaceMemberClient

	// lazily loaded.
	client     *Client
	clientOnce sync.Once
	// ctx lives for the life of the transaction. It is
	// the same context used by the underlying connection.
	ctx context.Context
}

type (
	// Committer is the interface that wraps the Commit method.
	Committer interface {
		Commit(context.Context, *Tx) error
	}

	// The CommitFunc type is an adapter to allow the use of ordinary
	// function as a Committer. If f is a function with the appropriate
	// signature, CommitFunc(f) is a Committer that calls f.
	CommitFunc func(context.Context, *Tx) error

	// CommitHook defines the "commit middleware". A function that gets a Committer
	// and returns a Committer. For example:
	//
	//	hook := func(next ent.Committer) ent.Committer {
	//		return ent.CommitFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Commit(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	CommitHook func(Committer) Committer
)

// Commit calls f(ctx, m).
func (f CommitFunc) Commit(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Commit commits the transaction.
func (tx *Tx) Commit() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Committer = CommitFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Commit()
	})
	txDriver.mu.Lock()
	hooks := append([]CommitHook(nil), txDriver.onCommit...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Commit(tx.ctx, tx)
}

// OnCommit adds a hook to call on commit.
func (tx *Tx) OnCommit(f CommitHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onCommit = append(txDriver.onCommit, f)
	txDriver.mu.Unlock()
}

type (
	// Rollbacker is the interface that wraps the Rollback method.
	Rollbacker interface {
		Rollback(context.Context, *Tx) error
	}

	// The RollbackFunc type is an adapter to allow the use of ordinary
	// function as a Rollbacker. If f is a function with the appropriate
	// signature, RollbackFunc(f) is a Rollbacker that calls f.
	RollbackFunc func(context.Context, *Tx) error

	// RollbackHook defines the "rollback middleware". A function that gets a Rollbacker
	// and returns a Rollbacker. For example:
	//
	//	hook := func(next ent.Rollbacker) ent.Rollbacker {
	//		return ent.RollbackFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Rollback(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	RollbackHook func(Rollbacker) Rollbacker
)

// Rollback calls f(ctx, m).
func (f RollbackFunc) Rollback(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Rollback rollbacks the transaction.
func (tx *Tx) Rollback() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Rollbacker = RollbackFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Rollback()
	})
	txDriver.mu.Lock()
	hooks := append([]RollbackHook(nil), txDriver.onRollback...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Rollback(tx.ctx, tx)
}

// OnRollback adds a hook to call on rollback.
func (tx *Tx) OnRollback(f RollbackHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onRollback = append(txDriver.onRollback, f)
	txDriver.mu.Unlock()
}

// Client returns a Client that binds to current transaction.
func (tx *Tx) Client() *Client {
	tx.clientOnce.Do(func() {
		tx.client = &Client{config: tx.config}
		tx.client.init()
	})
	return tx.client
}

func (tx *Tx) init() {
	tx.APIToken = NewAPITokenClient(tx.config)
	tx.Activity = NewActivityClient(tx.config)
	tx.AuthChallenge = NewAuthChallengeClient(tx.config)
	tx.AuthRateLimit = NewAuthRateLimitClient(tx.config)
	tx.Comment = NewCommentClient(tx.config)
	tx.Cycle = NewCycleClient(tx.config)
	tx.CycleItem = NewCycleItemClient(tx.config)
	tx.Estimate = NewEstimateClient(tx.config)
	tx.EstimatePoint = NewEstimatePointClient(tx.config)
	tx.Export = NewExportClient(tx.config)
	tx.Favorite = NewFavoriteClient(tx.config)
	tx.FileAsset = NewFileAssetClient(tx.config)
	tx.Instance = NewInstanceClient(tx.config)
	tx.IntakeItem = NewIntakeItemClient(tx.config)
	tx.Invitation = NewInvitationClient(tx.config)
	tx.Label = NewLabelClient(tx.config)
	tx.Module = NewModuleClient(tx.config)
	tx.ModuleItem = NewModuleItemClient(tx.config)
	tx.ModuleLink = NewModuleLinkClient(tx.config)
	tx.ModuleMember = NewModuleMemberClient(tx.config)
	tx.Notification = NewNotificationClient(tx.config)
	tx.OAuthAccount = NewOAuthAccountClient(tx.config)
	tx.OutboxEvent = NewOutboxEventClient(tx.config)
	tx.Page = NewPageClient(tx.config)
	tx.PageComment = NewPageCommentClient(tx.config)
	tx.PageVersion = NewPageVersionClient(tx.config)
	tx.Preference = NewPreferenceClient(tx.config)
	tx.Project = NewProjectClient(tx.config)
	tx.ProjectMember = NewProjectMemberClient(tx.config)
	tx.PublicSite = NewPublicSiteClient(tx.config)
	tx.PublicVote = NewPublicVoteClient(tx.config)
	tx.Reaction = NewReactionClient(tx.config)
	tx.RecentVisit = NewRecentVisitClient(tx.config)
	tx.SavedAnalysis = NewSavedAnalysisClient(tx.config)
	tx.SavedView = NewSavedViewClient(tx.config)
	tx.Session = NewSessionClient(tx.config)
	tx.State = NewStateClient(tx.config)
	tx.Sticky = NewStickyClient(tx.config)
	tx.User = NewUserClient(tx.config)
	tx.Webhook = NewWebhookClient(tx.config)
	tx.WebhookDelivery = NewWebhookDeliveryClient(tx.config)
	tx.WorkItem = NewWorkItemClient(tx.config)
	tx.WorkItemAssignee = NewWorkItemAssigneeClient(tx.config)
	tx.WorkItemLabel = NewWorkItemLabelClient(tx.config)
	tx.WorkItemLink = NewWorkItemLinkClient(tx.config)
	tx.WorkItemRelation = NewWorkItemRelationClient(tx.config)
	tx.WorkItemSubscriber = NewWorkItemSubscriberClient(tx.config)
	tx.WorkItemVersion = NewWorkItemVersionClient(tx.config)
	tx.Workspace = NewWorkspaceClient(tx.config)
	tx.WorkspaceMember = NewWorkspaceMemberClient(tx.config)
}

// txDriver wraps the given dialect.Tx with a nop dialect.Driver implementation.
// The idea is to support transactions without adding any extra code to the builders.
// When a builder calls to driver.Tx(), it gets the same dialect.Tx instance.
// Commit and Rollback are nop for the internal builders and the user must call one
// of them in order to commit or rollback the transaction.
//
// If a closed transaction is embedded in one of the generated entities, and the entity
// applies a query, for example: APIToken.QueryXXX(), the query will be executed
// through the driver which created this transaction.
//
// Note that txDriver is not goroutine safe.
type txDriver struct {
	// the driver we started the transaction from.
	drv dialect.Driver
	// tx is the underlying transaction.
	tx dialect.Tx
	// completion hooks.
	mu         sync.Mutex
	onCommit   []CommitHook
	onRollback []RollbackHook
}

// newTx creates a new transactional driver.
func newTx(ctx context.Context, drv dialect.Driver) (*txDriver, error) {
	tx, err := drv.Tx(ctx)
	if err != nil {
		return nil, err
	}
	return &txDriver{tx: tx, drv: drv}, nil
}

// Tx returns the transaction wrapper (txDriver) to avoid Commit or Rollback calls
// from the internal builders. Should be called only by the internal builders.
func (tx *txDriver) Tx(context.Context) (dialect.Tx, error) { return tx, nil }

// Dialect returns the dialect of the driver we started the transaction from.
func (tx *txDriver) Dialect() string { return tx.drv.Dialect() }

// Close is a nop close.
func (*txDriver) Close() error { return nil }

// Commit is a nop commit for the internal builders.
// User must call `Tx.Commit` in order to commit the transaction.
func (*txDriver) Commit() error { return nil }

// Rollback is a nop rollback for the internal builders.
// User must call `Tx.Rollback` in order to rollback the transaction.
func (*txDriver) Rollback() error { return nil }

// Exec calls tx.Exec.
func (tx *txDriver) Exec(ctx context.Context, query string, args, v any) error {
	return tx.tx.Exec(ctx, query, args, v)
}

// Query calls tx.Query.
func (tx *txDriver) Query(ctx context.Context, query string, args, v any) error {
	return tx.tx.Query(ctx, query, args, v)
}

var _ dialect.Driver = (*txDriver)(nil)
