// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"my-jira/apps/api/ent/predicate"
	"my-jira/apps/api/ent/workitemsubscriber"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkItemSubscriberDelete is the builder for deleting a WorkItemSubscriber entity.
type WorkItemSubscriberDelete struct {
	config
	hooks    []Hook
	mutation *WorkItemSubscriberMutation
}

// Where appends a list predicates to the WorkItemSubscriberDelete builder.
func (_d *WorkItemSubscriberDelete) Where(ps ...predicate.WorkItemSubscriber) *WorkItemSubscriberDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *WorkItemSubscriberDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WorkItemSubscriberDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *WorkItemSubscriberDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(workitemsubscriber.Table, sqlgraph.NewFieldSpec(workitemsubscriber.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// WorkItemSubscriberDeleteOne is the builder for deleting a single WorkItemSubscriber entity.
type WorkItemSubscriberDeleteOne struct {
	_d *WorkItemSubscriberDelete
}

// Where appends a list predicates to the WorkItemSubscriberDelete builder.
func (_d *WorkItemSubscriberDeleteOne) Where(ps ...predicate.WorkItemSubscriber) *WorkItemSubscriberDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *WorkItemSubscriberDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{workitemsubscriber.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WorkItemSubscriberDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
