// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"my-jira/apps/api/ent/predicate"
	"my-jira/apps/api/ent/workitemlabel"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WorkItemLabelUpdate is the builder for updating WorkItemLabel entities.
type WorkItemLabelUpdate struct {
	config
	hooks    []Hook
	mutation *WorkItemLabelMutation
}

// Where appends a list predicates to the WorkItemLabelUpdate builder.
func (_u *WorkItemLabelUpdate) Where(ps ...predicate.WorkItemLabel) *WorkItemLabelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkItemLabelUpdate) SetUpdatedAt(v time.Time) *WorkItemLabelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *WorkItemLabelUpdate) SetDeletedAt(v time.Time) *WorkItemLabelUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *WorkItemLabelUpdate) SetNillableDeletedAt(v *time.Time) *WorkItemLabelUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *WorkItemLabelUpdate) ClearDeletedAt() *WorkItemLabelUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *WorkItemLabelUpdate) SetWorkspaceID(v uuid.UUID) *WorkItemLabelUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *WorkItemLabelUpdate) SetNillableWorkspaceID(v *uuid.UUID) *WorkItemLabelUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *WorkItemLabelUpdate) SetProjectID(v uuid.UUID) *WorkItemLabelUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *WorkItemLabelUpdate) SetNillableProjectID(v *uuid.UUID) *WorkItemLabelUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetWorkItemID sets the "work_item_id" field.
func (_u *WorkItemLabelUpdate) SetWorkItemID(v uuid.UUID) *WorkItemLabelUpdate {
	_u.mutation.SetWorkItemID(v)
	return _u
}

// SetNillableWorkItemID sets the "work_item_id" field if the given value is not nil.
func (_u *WorkItemLabelUpdate) SetNillableWorkItemID(v *uuid.UUID) *WorkItemLabelUpdate {
	if v != nil {
		_u.SetWorkItemID(*v)
	}
	return _u
}

// SetLabelID sets the "label_id" field.
func (_u *WorkItemLabelUpdate) SetLabelID(v uuid.UUID) *WorkItemLabelUpdate {
	_u.mutation.SetLabelID(v)
	return _u
}

// SetNillableLabelID sets the "label_id" field if the given value is not nil.
func (_u *WorkItemLabelUpdate) SetNillableLabelID(v *uuid.UUID) *WorkItemLabelUpdate {
	if v != nil {
		_u.SetLabelID(*v)
	}
	return _u
}

// Mutation returns the WorkItemLabelMutation object of the builder.
func (_u *WorkItemLabelUpdate) Mutation() *WorkItemLabelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkItemLabelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkItemLabelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkItemLabelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkItemLabelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkItemLabelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workitemlabel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *WorkItemLabelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(workitemlabel.Table, workitemlabel.Columns, sqlgraph.NewFieldSpec(workitemlabel.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workitemlabel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(workitemlabel.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(workitemlabel.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(workitemlabel.FieldWorkspaceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(workitemlabel.FieldProjectID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.WorkItemID(); ok {
		_spec.SetField(workitemlabel.FieldWorkItemID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.LabelID(); ok {
		_spec.SetField(workitemlabel.FieldLabelID, field.TypeUUID, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workitemlabel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkItemLabelUpdateOne is the builder for updating a single WorkItemLabel entity.
type WorkItemLabelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkItemLabelMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkItemLabelUpdateOne) SetUpdatedAt(v time.Time) *WorkItemLabelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *WorkItemLabelUpdateOne) SetDeletedAt(v time.Time) *WorkItemLabelUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *WorkItemLabelUpdateOne) SetNillableDeletedAt(v *time.Time) *WorkItemLabelUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *WorkItemLabelUpdateOne) ClearDeletedAt() *WorkItemLabelUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *WorkItemLabelUpdateOne) SetWorkspaceID(v uuid.UUID) *WorkItemLabelUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *WorkItemLabelUpdateOne) SetNillableWorkspaceID(v *uuid.UUID) *WorkItemLabelUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *WorkItemLabelUpdateOne) SetProjectID(v uuid.UUID) *WorkItemLabelUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *WorkItemLabelUpdateOne) SetNillableProjectID(v *uuid.UUID) *WorkItemLabelUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetWorkItemID sets the "work_item_id" field.
func (_u *WorkItemLabelUpdateOne) SetWorkItemID(v uuid.UUID) *WorkItemLabelUpdateOne {
	_u.mutation.SetWorkItemID(v)
	return _u
}

// SetNillableWorkItemID sets the "work_item_id" field if the given value is not nil.
func (_u *WorkItemLabelUpdateOne) SetNillableWorkItemID(v *uuid.UUID) *WorkItemLabelUpdateOne {
	if v != nil {
		_u.SetWorkItemID(*v)
	}
	return _u
}

// SetLabelID sets the "label_id" field.
func (_u *WorkItemLabelUpdateOne) SetLabelID(v uuid.UUID) *WorkItemLabelUpdateOne {
	_u.mutation.SetLabelID(v)
	return _u
}

// SetNillableLabelID sets the "label_id" field if the given value is not nil.
func (_u *WorkItemLabelUpdateOne) SetNillableLabelID(v *uuid.UUID) *WorkItemLabelUpdateOne {
	if v != nil {
		_u.SetLabelID(*v)
	}
	return _u
}

// Mutation returns the WorkItemLabelMutation object of the builder.
func (_u *WorkItemLabelUpdateOne) Mutation() *WorkItemLabelMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkItemLabelUpdate builder.
func (_u *WorkItemLabelUpdateOne) Where(ps ...predicate.WorkItemLabel) *WorkItemLabelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkItemLabelUpdateOne) Select(field string, fields ...string) *WorkItemLabelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkItemLabel entity.
func (_u *WorkItemLabelUpdateOne) Save(ctx context.Context) (*WorkItemLabel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkItemLabelUpdateOne) SaveX(ctx context.Context) *WorkItemLabel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkItemLabelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkItemLabelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkItemLabelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workitemlabel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *WorkItemLabelUpdateOne) sqlSave(ctx context.Context) (_node *WorkItemLabel, err error) {
	_spec := sqlgraph.NewUpdateSpec(workitemlabel.Table, workitemlabel.Columns, sqlgraph.NewFieldSpec(workitemlabel.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkItemLabel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workitemlabel.FieldID)
		for _, f := range fields {
			if !workitemlabel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workitemlabel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workitemlabel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(workitemlabel.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(workitemlabel.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(workitemlabel.FieldWorkspaceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(workitemlabel.FieldProjectID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.WorkItemID(); ok {
		_spec.SetField(workitemlabel.FieldWorkItemID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.LabelID(); ok {
		_spec.SetField(workitemlabel.FieldLabelID, field.TypeUUID, value)
	}
	_node = &WorkItemLabel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workitemlabel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
