// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"my-jira/apps/api/ent/predicate"
	"my-jira/apps/api/ent/workitemversion"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WorkItemVersionUpdate is the builder for updating WorkItemVersion entities.
type WorkItemVersionUpdate struct {
	config
	hooks    []Hook
	mutation *WorkItemVersionMutation
}

// Where appends a list predicates to the WorkItemVersionUpdate builder.
func (_u *WorkItemVersionUpdate) Where(ps ...predicate.WorkItemVersion) *WorkItemVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkItemVersionUpdate) SetUpdatedAt(v time.Time) *WorkItemVersionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *WorkItemVersionUpdate) SetDeletedAt(v time.Time) *WorkItemVersionUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *WorkItemVersionUpdate) SetNillableDeletedAt(v *time.Time) *WorkItemVersionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *WorkItemVersionUpdate) ClearDeletedAt() *WorkItemVersionUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *WorkItemVersionUpdate) SetWorkspaceID(v uuid.UUID) *WorkItemVersionUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *WorkItemVersionUpdate) SetNillableWorkspaceID(v *uuid.UUID) *WorkItemVersionUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *WorkItemVersionUpdate) SetProjectID(v uuid.UUID) *WorkItemVersionUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *WorkItemVersionUpdate) SetNillableProjectID(v *uuid.UUID) *WorkItemVersionUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetWorkItemID sets the "work_item_id" field.
func (_u *WorkItemVersionUpdate) SetWorkItemID(v uuid.UUID) *WorkItemVersionUpdate {
	_u.mutation.SetWorkItemID(v)
	return _u
}

// SetNillableWorkItemID sets the "work_item_id" field if the given value is not nil.
func (_u *WorkItemVersionUpdate) SetNillableWorkItemID(v *uuid.UUID) *WorkItemVersionUpdate {
	if v != nil {
		_u.SetWorkItemID(*v)
	}
	return _u
}

// SetSavedBy sets the "saved_by" field.
func (_u *WorkItemVersionUpdate) SetSavedBy(v uuid.UUID) *WorkItemVersionUpdate {
	_u.mutation.SetSavedBy(v)
	return _u
}

// SetNillableSavedBy sets the "saved_by" field if the given value is not nil.
func (_u *WorkItemVersionUpdate) SetNillableSavedBy(v *uuid.UUID) *WorkItemVersionUpdate {
	if v != nil {
		_u.SetSavedBy(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *WorkItemVersionUpdate) SetVersion(v int64) *WorkItemVersionUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *WorkItemVersionUpdate) SetNillableVersion(v *int64) *WorkItemVersionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *WorkItemVersionUpdate) AddVersion(v int64) *WorkItemVersionUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetSnapshot sets the "snapshot" field.
func (_u *WorkItemVersionUpdate) SetSnapshot(v map[string]interface{}) *WorkItemVersionUpdate {
	_u.mutation.SetSnapshot(v)
	return _u
}

// Mutation returns the WorkItemVersionMutation object of the builder.
func (_u *WorkItemVersionUpdate) Mutation() *WorkItemVersionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkItemVersionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkItemVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkItemVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkItemVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkItemVersionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workitemversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *WorkItemVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(workitemversion.Table, workitemversion.Columns, sqlgraph.NewFieldSpec(workitemversion.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workitemversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(workitemversion.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(workitemversion.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(workitemversion.FieldWorkspaceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(workitemversion.FieldProjectID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.WorkItemID(); ok {
		_spec.SetField(workitemversion.FieldWorkItemID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.SavedBy(); ok {
		_spec.SetField(workitemversion.FieldSavedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(workitemversion.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(workitemversion.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Snapshot(); ok {
		_spec.SetField(workitemversion.FieldSnapshot, field.TypeJSON, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workitemversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkItemVersionUpdateOne is the builder for updating a single WorkItemVersion entity.
type WorkItemVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkItemVersionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkItemVersionUpdateOne) SetUpdatedAt(v time.Time) *WorkItemVersionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *WorkItemVersionUpdateOne) SetDeletedAt(v time.Time) *WorkItemVersionUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *WorkItemVersionUpdateOne) SetNillableDeletedAt(v *time.Time) *WorkItemVersionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *WorkItemVersionUpdateOne) ClearDeletedAt() *WorkItemVersionUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *WorkItemVersionUpdateOne) SetWorkspaceID(v uuid.UUID) *WorkItemVersionUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *WorkItemVersionUpdateOne) SetNillableWorkspaceID(v *uuid.UUID) *WorkItemVersionUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *WorkItemVersionUpdateOne) SetProjectID(v uuid.UUID) *WorkItemVersionUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *WorkItemVersionUpdateOne) SetNillableProjectID(v *uuid.UUID) *WorkItemVersionUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetWorkItemID sets the "work_item_id" field.
func (_u *WorkItemVersionUpdateOne) SetWorkItemID(v uuid.UUID) *WorkItemVersionUpdateOne {
	_u.mutation.SetWorkItemID(v)
	return _u
}

// SetNillableWorkItemID sets the "work_item_id" field if the given value is not nil.
func (_u *WorkItemVersionUpdateOne) SetNillableWorkItemID(v *uuid.UUID) *WorkItemVersionUpdateOne {
	if v != nil {
		_u.SetWorkItemID(*v)
	}
	return _u
}

// SetSavedBy sets the "saved_by" field.
func (_u *WorkItemVersionUpdateOne) SetSavedBy(v uuid.UUID) *WorkItemVersionUpdateOne {
	_u.mutation.SetSavedBy(v)
	return _u
}

// SetNillableSavedBy sets the "saved_by" field if the given value is not nil.
func (_u *WorkItemVersionUpdateOne) SetNillableSavedBy(v *uuid.UUID) *WorkItemVersionUpdateOne {
	if v != nil {
		_u.SetSavedBy(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *WorkItemVersionUpdateOne) SetVersion(v int64) *WorkItemVersionUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *WorkItemVersionUpdateOne) SetNillableVersion(v *int64) *WorkItemVersionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *WorkItemVersionUpdateOne) AddVersion(v int64) *WorkItemVersionUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetSnapshot sets the "snapshot" field.
func (_u *WorkItemVersionUpdateOne) SetSnapshot(v map[string]interface{}) *WorkItemVersionUpdateOne {
	_u.mutation.SetSnapshot(v)
	return _u
}

// Mutation returns the WorkItemVersionMutation object of the builder.
func (_u *WorkItemVersionUpdateOne) Mutation() *WorkItemVersionMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkItemVersionUpdate builder.
func (_u *WorkItemVersionUpdateOne) Where(ps ...predicate.WorkItemVersion) *WorkItemVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkItemVersionUpdateOne) Select(field string, fields ...string) *WorkItemVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkItemVersion entity.
func (_u *WorkItemVersionUpdateOne) Save(ctx context.Context) (*WorkItemVersion, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkItemVersionUpdateOne) SaveX(ctx context.Context) *WorkItemVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkItemVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkItemVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkItemVersionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workitemversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *WorkItemVersionUpdateOne) sqlSave(ctx context.Context) (_node *WorkItemVersion, err error) {
	_spec := sqlgraph.NewUpdateSpec(workitemversion.Table, workitemversion.Columns, sqlgraph.NewFieldSpec(workitemversion.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkItemVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workitemversion.FieldID)
		for _, f := range fields {
			if !workitemversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workitemversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workitemversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(workitemversion.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(workitemversion.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(workitemversion.FieldWorkspaceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(workitemversion.FieldProjectID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.WorkItemID(); ok {
		_spec.SetField(workitemversion.FieldWorkItemID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.SavedBy(); ok {
		_spec.SetField(workitemversion.FieldSavedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(workitemversion.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(workitemversion.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Snapshot(); ok {
		_spec.SetField(workitemversion.FieldSnapshot, field.TypeJSON, value)
	}
	_node = &WorkItemVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workitemversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
