// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"my-jira/apps/api/ent/workspacemember"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WorkspaceMemberCreate is the builder for creating a WorkspaceMember entity.
type WorkspaceMemberCreate struct {
	config
	mutation *WorkspaceMemberMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *WorkspaceMemberCreate) SetCreatedAt(v time.Time) *WorkspaceMemberCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WorkspaceMemberCreate) SetNillableCreatedAt(v *time.Time) *WorkspaceMemberCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WorkspaceMemberCreate) SetUpdatedAt(v time.Time) *WorkspaceMemberCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WorkspaceMemberCreate) SetNillableUpdatedAt(v *time.Time) *WorkspaceMemberCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *WorkspaceMemberCreate) SetDeletedAt(v time.Time) *WorkspaceMemberCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *WorkspaceMemberCreate) SetNillableDeletedAt(v *time.Time) *WorkspaceMemberCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *WorkspaceMemberCreate) SetWorkspaceID(v uuid.UUID) *WorkspaceMemberCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *WorkspaceMemberCreate) SetUserID(v uuid.UUID) *WorkspaceMemberCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *WorkspaceMemberCreate) SetRole(v int) *WorkspaceMemberCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *WorkspaceMemberCreate) SetNillableRole(v *int) *WorkspaceMemberCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *WorkspaceMemberCreate) SetIsActive(v bool) *WorkspaceMemberCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *WorkspaceMemberCreate) SetNillableIsActive(v *bool) *WorkspaceMemberCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WorkspaceMemberCreate) SetID(v uuid.UUID) *WorkspaceMemberCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *WorkspaceMemberCreate) SetNillableID(v *uuid.UUID) *WorkspaceMemberCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the WorkspaceMemberMutation object of the builder.
func (_c *WorkspaceMemberCreate) Mutation() *WorkspaceMemberMutation {
	return _c.mutation
}

// Save creates the WorkspaceMember in the database.
func (_c *WorkspaceMemberCreate) Save(ctx context.Context) (*WorkspaceMember, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkspaceMemberCreate) SaveX(ctx context.Context) *WorkspaceMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkspaceMemberCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := workspacemember.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := workspacemember.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Role(); !ok {
		v := workspacemember.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := workspacemember.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := workspacemember.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkspaceMemberCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WorkspaceMember.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WorkspaceMember.updated_at"`)}
	}
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "WorkspaceMember.workspace_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "WorkspaceMember.user_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "WorkspaceMember.role"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "WorkspaceMember.is_active"`)}
	}
	return nil
}

func (_c *WorkspaceMemberCreate) sqlSave(ctx context.Context) (*WorkspaceMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkspaceMemberCreate) createSpec() (*WorkspaceMember, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkspaceMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(workspacemember.Table, sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(workspacemember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(workspacemember.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(workspacemember.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.WorkspaceID(); ok {
		_spec.SetField(workspacemember.FieldWorkspaceID, field.TypeUUID, value)
		_node.WorkspaceID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(workspacemember.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(workspacemember.FieldRole, field.TypeInt, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(workspacemember.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	return _node, _spec
}

// WorkspaceMemberCreateBulk is the builder for creating many WorkspaceMember entities in bulk.
type WorkspaceMemberCreateBulk struct {
	config
	err      error
	builders []*WorkspaceMemberCreate
}

// Save creates the WorkspaceMember entities in the database.
func (_c *WorkspaceMemberCreateBulk) Save(ctx context.Context) ([]*WorkspaceMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WorkspaceMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkspaceMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkspaceMemberCreateBulk) SaveX(ctx context.Context) []*WorkspaceMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkspaceMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkspaceMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
