// Code generated by ent, DO NOT EDIT.

package savedview

import (
	"my-jira/apps/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldDeletedAt, v))
}

// WorkspaceID applies equality check predicate on the "workspace_id" field. It's identical to WorkspaceIDEQ.
func WorkspaceID(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldWorkspaceID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldProjectID, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldOwnerID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldDescription, v))
}

// Layout applies equality check predicate on the "layout" field. It's identical to LayoutEQ.
func Layout(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldLayout, v))
}

// IsPrivate applies equality check predicate on the "is_private" field. It's identical to IsPrivateEQ.
func IsPrivate(v bool) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldIsPrivate, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v float64) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldPosition, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SavedView {
	return predicate.SavedView(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SavedView {
	return predicate.SavedView(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SavedView {
	return predicate.SavedView(sql.FieldNotNull(FieldDeletedAt))
}

// WorkspaceIDEQ applies the EQ predicate on the "workspace_id" field.
func WorkspaceIDEQ(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldWorkspaceID, v))
}

// WorkspaceIDNEQ applies the NEQ predicate on the "workspace_id" field.
func WorkspaceIDNEQ(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldNEQ(FieldWorkspaceID, v))
}

// WorkspaceIDIn applies the In predicate on the "workspace_id" field.
func WorkspaceIDIn(vs ...uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDNotIn applies the NotIn predicate on the "workspace_id" field.
func WorkspaceIDNotIn(vs ...uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldNotIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDGT applies the GT predicate on the "workspace_id" field.
func WorkspaceIDGT(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldGT(FieldWorkspaceID, v))
}

// WorkspaceIDGTE applies the GTE predicate on the "workspace_id" field.
func WorkspaceIDGTE(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldGTE(FieldWorkspaceID, v))
}

// WorkspaceIDLT applies the LT predicate on the "workspace_id" field.
func WorkspaceIDLT(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldLT(FieldWorkspaceID, v))
}

// WorkspaceIDLTE applies the LTE predicate on the "workspace_id" field.
func WorkspaceIDLTE(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldLTE(FieldWorkspaceID, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDIsNil applies the IsNil predicate on the "project_id" field.
func ProjectIDIsNil() predicate.SavedView {
	return predicate.SavedView(sql.FieldIsNull(FieldProjectID))
}

// ProjectIDNotNil applies the NotNil predicate on the "project_id" field.
func ProjectIDNotNil() predicate.SavedView {
	return predicate.SavedView(sql.FieldNotNull(FieldProjectID))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v uuid.UUID) predicate.SavedView {
	return predicate.SavedView(sql.FieldLTE(FieldOwnerID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SavedView {
	return predicate.SavedView(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SavedView {
	return predicate.SavedView(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.SavedView {
	return predicate.SavedView(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.SavedView {
	return predicate.SavedView(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldContainsFold(FieldDescription, v))
}

// LayoutEQ applies the EQ predicate on the "layout" field.
func LayoutEQ(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldLayout, v))
}

// LayoutNEQ applies the NEQ predicate on the "layout" field.
func LayoutNEQ(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldNEQ(FieldLayout, v))
}

// LayoutIn applies the In predicate on the "layout" field.
func LayoutIn(vs ...string) predicate.SavedView {
	return predicate.SavedView(sql.FieldIn(FieldLayout, vs...))
}

// LayoutNotIn applies the NotIn predicate on the "layout" field.
func LayoutNotIn(vs ...string) predicate.SavedView {
	return predicate.SavedView(sql.FieldNotIn(FieldLayout, vs...))
}

// LayoutGT applies the GT predicate on the "layout" field.
func LayoutGT(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldGT(FieldLayout, v))
}

// LayoutGTE applies the GTE predicate on the "layout" field.
func LayoutGTE(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldGTE(FieldLayout, v))
}

// LayoutLT applies the LT predicate on the "layout" field.
func LayoutLT(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldLT(FieldLayout, v))
}

// LayoutLTE applies the LTE predicate on the "layout" field.
func LayoutLTE(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldLTE(FieldLayout, v))
}

// LayoutContains applies the Contains predicate on the "layout" field.
func LayoutContains(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldContains(FieldLayout, v))
}

// LayoutHasPrefix applies the HasPrefix predicate on the "layout" field.
func LayoutHasPrefix(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldHasPrefix(FieldLayout, v))
}

// LayoutHasSuffix applies the HasSuffix predicate on the "layout" field.
func LayoutHasSuffix(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldHasSuffix(FieldLayout, v))
}

// LayoutEqualFold applies the EqualFold predicate on the "layout" field.
func LayoutEqualFold(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldEqualFold(FieldLayout, v))
}

// LayoutContainsFold applies the ContainsFold predicate on the "layout" field.
func LayoutContainsFold(v string) predicate.SavedView {
	return predicate.SavedView(sql.FieldContainsFold(FieldLayout, v))
}

// IsPrivateEQ applies the EQ predicate on the "is_private" field.
func IsPrivateEQ(v bool) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldIsPrivate, v))
}

// IsPrivateNEQ applies the NEQ predicate on the "is_private" field.
func IsPrivateNEQ(v bool) predicate.SavedView {
	return predicate.SavedView(sql.FieldNEQ(FieldIsPrivate, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v float64) predicate.SavedView {
	return predicate.SavedView(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v float64) predicate.SavedView {
	return predicate.SavedView(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...float64) predicate.SavedView {
	return predicate.SavedView(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...float64) predicate.SavedView {
	return predicate.SavedView(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v float64) predicate.SavedView {
	return predicate.SavedView(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v float64) predicate.SavedView {
	return predicate.SavedView(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v float64) predicate.SavedView {
	return predicate.SavedView(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v float64) predicate.SavedView {
	return predicate.SavedView(sql.FieldLTE(FieldPosition, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SavedView) predicate.SavedView {
	return predicate.SavedView(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SavedView) predicate.SavedView {
	return predicate.SavedView(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SavedView) predicate.SavedView {
	return predicate.SavedView(sql.NotPredicates(p))
}
