// Code generated by ent, DO NOT EDIT.

package publicsite

import (
	"my-jira/apps/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldDeletedAt, v))
}

// WorkspaceID applies equality check predicate on the "workspace_id" field. It's identical to WorkspaceIDEQ.
func WorkspaceID(v uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldWorkspaceID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldProjectID, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldSlug, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldDescription, v))
}

// IsEnabled applies equality check predicate on the "is_enabled" field. It's identical to IsEnabledEQ.
func IsEnabled(v bool) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldIsEnabled, v))
}

// CommentsEnabled applies equality check predicate on the "comments_enabled" field. It's identical to CommentsEnabledEQ.
func CommentsEnabled(v bool) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldCommentsEnabled, v))
}

// ReactionsEnabled applies equality check predicate on the "reactions_enabled" field. It's identical to ReactionsEnabledEQ.
func ReactionsEnabled(v bool) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldReactionsEnabled, v))
}

// VotesEnabled applies equality check predicate on the "votes_enabled" field. It's identical to VotesEnabledEQ.
func VotesEnabled(v bool) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldVotesEnabled, v))
}

// IntakeEnabled applies equality check predicate on the "intake_enabled" field. It's identical to IntakeEnabledEQ.
func IntakeEnabled(v bool) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldIntakeEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.PublicSite {
	return predicate.PublicSite(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNotNull(FieldDeletedAt))
}

// WorkspaceIDEQ applies the EQ predicate on the "workspace_id" field.
func WorkspaceIDEQ(v uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldWorkspaceID, v))
}

// WorkspaceIDNEQ applies the NEQ predicate on the "workspace_id" field.
func WorkspaceIDNEQ(v uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNEQ(FieldWorkspaceID, v))
}

// WorkspaceIDIn applies the In predicate on the "workspace_id" field.
func WorkspaceIDIn(vs ...uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDNotIn applies the NotIn predicate on the "workspace_id" field.
func WorkspaceIDNotIn(vs ...uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNotIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDGT applies the GT predicate on the "workspace_id" field.
func WorkspaceIDGT(v uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGT(FieldWorkspaceID, v))
}

// WorkspaceIDGTE applies the GTE predicate on the "workspace_id" field.
func WorkspaceIDGTE(v uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGTE(FieldWorkspaceID, v))
}

// WorkspaceIDLT applies the LT predicate on the "workspace_id" field.
func WorkspaceIDLT(v uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLT(FieldWorkspaceID, v))
}

// WorkspaceIDLTE applies the LTE predicate on the "workspace_id" field.
func WorkspaceIDLTE(v uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLTE(FieldWorkspaceID, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v uuid.UUID) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLTE(FieldProjectID, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldContainsFold(FieldSlug, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldContainsFold(FieldDescription, v))
}

// IsEnabledEQ applies the EQ predicate on the "is_enabled" field.
func IsEnabledEQ(v bool) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldIsEnabled, v))
}

// IsEnabledNEQ applies the NEQ predicate on the "is_enabled" field.
func IsEnabledNEQ(v bool) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNEQ(FieldIsEnabled, v))
}

// CommentsEnabledEQ applies the EQ predicate on the "comments_enabled" field.
func CommentsEnabledEQ(v bool) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldCommentsEnabled, v))
}

// CommentsEnabledNEQ applies the NEQ predicate on the "comments_enabled" field.
func CommentsEnabledNEQ(v bool) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNEQ(FieldCommentsEnabled, v))
}

// ReactionsEnabledEQ applies the EQ predicate on the "reactions_enabled" field.
func ReactionsEnabledEQ(v bool) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldReactionsEnabled, v))
}

// ReactionsEnabledNEQ applies the NEQ predicate on the "reactions_enabled" field.
func ReactionsEnabledNEQ(v bool) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNEQ(FieldReactionsEnabled, v))
}

// VotesEnabledEQ applies the EQ predicate on the "votes_enabled" field.
func VotesEnabledEQ(v bool) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldVotesEnabled, v))
}

// VotesEnabledNEQ applies the NEQ predicate on the "votes_enabled" field.
func VotesEnabledNEQ(v bool) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNEQ(FieldVotesEnabled, v))
}

// IntakeEnabledEQ applies the EQ predicate on the "intake_enabled" field.
func IntakeEnabledEQ(v bool) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldEQ(FieldIntakeEnabled, v))
}

// IntakeEnabledNEQ applies the NEQ predicate on the "intake_enabled" field.
func IntakeEnabledNEQ(v bool) predicate.PublicSite {
	return predicate.PublicSite(sql.FieldNEQ(FieldIntakeEnabled, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PublicSite) predicate.PublicSite {
	return predicate.PublicSite(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PublicSite) predicate.PublicSite {
	return predicate.PublicSite(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PublicSite) predicate.PublicSite {
	return predicate.PublicSite(sql.NotPredicates(p))
}
