// Code generated by ent, DO NOT EDIT.

package reaction

import (
	"my-jira/apps/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldDeletedAt, v))
}

// WorkspaceID applies equality check predicate on the "workspace_id" field. It's identical to WorkspaceIDEQ.
func WorkspaceID(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldWorkspaceID, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldProjectID, v))
}

// WorkItemID applies equality check predicate on the "work_item_id" field. It's identical to WorkItemIDEQ.
func WorkItemID(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldWorkItemID, v))
}

// CommentID applies equality check predicate on the "comment_id" field. It's identical to CommentIDEQ.
func CommentID(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldCommentID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldUserID, v))
}

// Emoji applies equality check predicate on the "emoji" field. It's identical to EmojiEQ.
func Emoji(v string) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldEmoji, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Reaction {
	return predicate.Reaction(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Reaction {
	return predicate.Reaction(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Reaction {
	return predicate.Reaction(sql.FieldNotNull(FieldDeletedAt))
}

// WorkspaceIDEQ applies the EQ predicate on the "workspace_id" field.
func WorkspaceIDEQ(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldWorkspaceID, v))
}

// WorkspaceIDNEQ applies the NEQ predicate on the "workspace_id" field.
func WorkspaceIDNEQ(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldNEQ(FieldWorkspaceID, v))
}

// WorkspaceIDIn applies the In predicate on the "workspace_id" field.
func WorkspaceIDIn(vs ...uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDNotIn applies the NotIn predicate on the "workspace_id" field.
func WorkspaceIDNotIn(vs ...uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldNotIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDGT applies the GT predicate on the "workspace_id" field.
func WorkspaceIDGT(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldGT(FieldWorkspaceID, v))
}

// WorkspaceIDGTE applies the GTE predicate on the "workspace_id" field.
func WorkspaceIDGTE(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldGTE(FieldWorkspaceID, v))
}

// WorkspaceIDLT applies the LT predicate on the "workspace_id" field.
func WorkspaceIDLT(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldLT(FieldWorkspaceID, v))
}

// WorkspaceIDLTE applies the LTE predicate on the "workspace_id" field.
func WorkspaceIDLTE(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldLTE(FieldWorkspaceID, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldLTE(FieldProjectID, v))
}

// WorkItemIDEQ applies the EQ predicate on the "work_item_id" field.
func WorkItemIDEQ(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldWorkItemID, v))
}

// WorkItemIDNEQ applies the NEQ predicate on the "work_item_id" field.
func WorkItemIDNEQ(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldNEQ(FieldWorkItemID, v))
}

// WorkItemIDIn applies the In predicate on the "work_item_id" field.
func WorkItemIDIn(vs ...uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldIn(FieldWorkItemID, vs...))
}

// WorkItemIDNotIn applies the NotIn predicate on the "work_item_id" field.
func WorkItemIDNotIn(vs ...uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldNotIn(FieldWorkItemID, vs...))
}

// WorkItemIDGT applies the GT predicate on the "work_item_id" field.
func WorkItemIDGT(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldGT(FieldWorkItemID, v))
}

// WorkItemIDGTE applies the GTE predicate on the "work_item_id" field.
func WorkItemIDGTE(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldGTE(FieldWorkItemID, v))
}

// WorkItemIDLT applies the LT predicate on the "work_item_id" field.
func WorkItemIDLT(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldLT(FieldWorkItemID, v))
}

// WorkItemIDLTE applies the LTE predicate on the "work_item_id" field.
func WorkItemIDLTE(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldLTE(FieldWorkItemID, v))
}

// WorkItemIDIsNil applies the IsNil predicate on the "work_item_id" field.
func WorkItemIDIsNil() predicate.Reaction {
	return predicate.Reaction(sql.FieldIsNull(FieldWorkItemID))
}

// WorkItemIDNotNil applies the NotNil predicate on the "work_item_id" field.
func WorkItemIDNotNil() predicate.Reaction {
	return predicate.Reaction(sql.FieldNotNull(FieldWorkItemID))
}

// CommentIDEQ applies the EQ predicate on the "comment_id" field.
func CommentIDEQ(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldCommentID, v))
}

// CommentIDNEQ applies the NEQ predicate on the "comment_id" field.
func CommentIDNEQ(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldNEQ(FieldCommentID, v))
}

// CommentIDIn applies the In predicate on the "comment_id" field.
func CommentIDIn(vs ...uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldIn(FieldCommentID, vs...))
}

// CommentIDNotIn applies the NotIn predicate on the "comment_id" field.
func CommentIDNotIn(vs ...uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldNotIn(FieldCommentID, vs...))
}

// CommentIDGT applies the GT predicate on the "comment_id" field.
func CommentIDGT(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldGT(FieldCommentID, v))
}

// CommentIDGTE applies the GTE predicate on the "comment_id" field.
func CommentIDGTE(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldGTE(FieldCommentID, v))
}

// CommentIDLT applies the LT predicate on the "comment_id" field.
func CommentIDLT(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldLT(FieldCommentID, v))
}

// CommentIDLTE applies the LTE predicate on the "comment_id" field.
func CommentIDLTE(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldLTE(FieldCommentID, v))
}

// CommentIDIsNil applies the IsNil predicate on the "comment_id" field.
func CommentIDIsNil() predicate.Reaction {
	return predicate.Reaction(sql.FieldIsNull(FieldCommentID))
}

// CommentIDNotNil applies the NotNil predicate on the "comment_id" field.
func CommentIDNotNil() predicate.Reaction {
	return predicate.Reaction(sql.FieldNotNull(FieldCommentID))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.Reaction {
	return predicate.Reaction(sql.FieldLTE(FieldUserID, v))
}

// EmojiEQ applies the EQ predicate on the "emoji" field.
func EmojiEQ(v string) predicate.Reaction {
	return predicate.Reaction(sql.FieldEQ(FieldEmoji, v))
}

// EmojiNEQ applies the NEQ predicate on the "emoji" field.
func EmojiNEQ(v string) predicate.Reaction {
	return predicate.Reaction(sql.FieldNEQ(FieldEmoji, v))
}

// EmojiIn applies the In predicate on the "emoji" field.
func EmojiIn(vs ...string) predicate.Reaction {
	return predicate.Reaction(sql.FieldIn(FieldEmoji, vs...))
}

// EmojiNotIn applies the NotIn predicate on the "emoji" field.
func EmojiNotIn(vs ...string) predicate.Reaction {
	return predicate.Reaction(sql.FieldNotIn(FieldEmoji, vs...))
}

// EmojiGT applies the GT predicate on the "emoji" field.
func EmojiGT(v string) predicate.Reaction {
	return predicate.Reaction(sql.FieldGT(FieldEmoji, v))
}

// EmojiGTE applies the GTE predicate on the "emoji" field.
func EmojiGTE(v string) predicate.Reaction {
	return predicate.Reaction(sql.FieldGTE(FieldEmoji, v))
}

// EmojiLT applies the LT predicate on the "emoji" field.
func EmojiLT(v string) predicate.Reaction {
	return predicate.Reaction(sql.FieldLT(FieldEmoji, v))
}

// EmojiLTE applies the LTE predicate on the "emoji" field.
func EmojiLTE(v string) predicate.Reaction {
	return predicate.Reaction(sql.FieldLTE(FieldEmoji, v))
}

// EmojiContains applies the Contains predicate on the "emoji" field.
func EmojiContains(v string) predicate.Reaction {
	return predicate.Reaction(sql.FieldContains(FieldEmoji, v))
}

// EmojiHasPrefix applies the HasPrefix predicate on the "emoji" field.
func EmojiHasPrefix(v string) predicate.Reaction {
	return predicate.Reaction(sql.FieldHasPrefix(FieldEmoji, v))
}

// EmojiHasSuffix applies the HasSuffix predicate on the "emoji" field.
func EmojiHasSuffix(v string) predicate.Reaction {
	return predicate.Reaction(sql.FieldHasSuffix(FieldEmoji, v))
}

// EmojiEqualFold applies the EqualFold predicate on the "emoji" field.
func EmojiEqualFold(v string) predicate.Reaction {
	return predicate.Reaction(sql.FieldEqualFold(FieldEmoji, v))
}

// EmojiContainsFold applies the ContainsFold predicate on the "emoji" field.
func EmojiContainsFold(v string) predicate.Reaction {
	return predicate.Reaction(sql.FieldContainsFold(FieldEmoji, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Reaction) predicate.Reaction {
	return predicate.Reaction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Reaction) predicate.Reaction {
	return predicate.Reaction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Reaction) predicate.Reaction {
	return predicate.Reaction(sql.NotPredicates(p))
}
